//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 7/31/2019 1:07:49 PM by user jmansfield
//
//     Type: ENTITY
//     Entity: AGREEMENTS
//     Application: CORE
//     Environment: dvcoll_wstst01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "Agreements")]
	[ColleagueDataContract(GeneratedDateTime = "7/31/2019 1:07:49 PM", User = "jmansfield")]
	[EntityDataContract(EntityName = "AGREEMENTS", EntityType = "PHYS")]
	public class Agreements : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: AGR.DESCRIPTION
		/// </summary>
		[DataMember(Order = 0, Name = "AGR.DESCRIPTION")]
		public string AgrDescription { get; set; }
		
		/// <summary>
		/// CDD Name: AGR.ALLOW.DECLINE
		/// </summary>
		[DataMember(Order = 1, Name = "AGR.ALLOW.DECLINE")]
		public string AgrAllowDecline { get; set; }
		
		/// <summary>
		/// CDD Name: AGR.DEFAULT.PERIOD
		/// </summary>
		[DataMember(Order = 2, Name = "AGR.DEFAULT.PERIOD")]
		public string AgrDefaultPeriod { get; set; }
		
		/// <summary>
		/// CDD Name: AGR.DEFAULT.DUE.DATE
		/// </summary>
		[DataMember(Order = 3, Name = "AGR.DEFAULT.DUE.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? AgrDefaultDueDate { get; set; }
		
		/// <summary>
		/// CDD Name: AGR.TEXT
		/// </summary>
		[DataMember(Order = 4, Name = "AGR.TEXT")]
		public string AgrText { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}