//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 11/22/2019 1:54:10 AM by user vinay_an
//
//     Type: ENTITY
//     Entity: BOX.CODES
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "BoxCodes")]
	[ColleagueDataContract(GeneratedDateTime = "11/22/2019 1:54:10 AM", User = "vinay_an")]
	[EntityDataContract(EntityName = "BOX.CODES", EntityType = "PHYS")]
	public class BoxCodes : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: BXC.DESC
		/// </summary>
		[DataMember(Order = 0, Name = "BXC.DESC")]
		public string BxcDesc { get; set; }
		
		/// <summary>
		/// CDD Name: BXC.TAX.FORM
		/// </summary>
		[DataMember(Order = 1, Name = "BXC.TAX.FORM")]
		public string BxcTaxForm { get; set; }
		
		/// <summary>
		/// CDD Name: BXC.BOX.NUMBER
		/// </summary>
		[DataMember(Order = 2, Name = "BXC.BOX.NUMBER")]
		public string BxcBoxNumber { get; set; }
		
		/// <summary>
		/// CDD Name: BXC.COUNTRY
		/// </summary>
		[DataMember(Order = 30, Name = "BXC.COUNTRY")]
		public string BxcCountry { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}