//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 1/10/2020 12:29:58 PM by user ramyajoshi
//
//     Type: ENTITY
//     Entity: CASE.CLOSURE.REASONS
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "CaseClosureReasons")]
	[ColleagueDataContract(GeneratedDateTime = "1/10/2020 12:29:58 PM", User = "ramyajoshi")]
	[EntityDataContract(EntityName = "CASE.CLOSURE.REASONS", EntityType = "PHYS")]
	public class CaseClosureReasons : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: CCRE.DESCRIPTION
		/// </summary>
		[DataMember(Order = 0, Name = "CCRE.DESCRIPTION")]
		public string CcreDescription { get; set; }
		
		/// <summary>
		/// CDD Name: CCRE.CATEGORIES
		/// </summary>
		[DataMember(Order = 1, Name = "CCRE.CATEGORIES")]
		public List<string> CcreCategories { get; set; }
		
		/// <summary>
		/// CDD Name: CCRE.NAME
		/// </summary>
		[DataMember(Order = 6, Name = "CCRE.NAME")]
		public string CcreName { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}