//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 7/6/2020 3:25:48 PM by user dvcoll-srm
//
//     Type: ENTITY
//     Entity: GEN.LDGR
//     Application: CF
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "GenLdgrBase")]
	[ColleagueDataContract(GeneratedDateTime = "7/6/2020 3:25:48 PM", User = "dvcoll-srm")]
	[EntityDataContract(EntityName = "GEN.LDGR", EntityType = "PHYS")]
	public class GenLdgrBase : IColleagueGuidEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
	
		/// <summary>
		/// Record GUID
		/// </summary>
		[DataMember(Name = "RecordGuid")]
		public string RecordGuid { get; set; }

		/// <summary>
		/// Record Model Name
		/// </summary>
		[DataMember(Name = "RecordModelName")]
		public string RecordModelName { get; set; }	
		
		/// <summary>
		/// CDD Name: GEN.LDGR.FILECLASS
		/// </summary>
		[DataMember(Order = 7, Name = "GEN.LDGR.FILECLASS")]
		public List<string> GenLdgrFileclass { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.FNAME
		/// </summary>
		[DataMember(Order = 8, Name = "GEN.LDGR.FNAME")]
		public List<string> GenLdgrFname { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.FILESTATUS
		/// </summary>
		[DataMember(Order = 9, Name = "GEN.LDGR.FILESTATUS")]
		public List<string> GenLdgrFilestatus { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.LOCATION
		/// </summary>
		[DataMember(Order = 10, Name = "GEN.LDGR.LOCATION")]
		public List<string> GenLdgrLocation { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.STATUS.DATE
		/// </summary>
		[DataMember(Order = 11, Name = "GEN.LDGR.STATUS.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<DateTime?> GenLdgrStatusDate { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.INDEX1
		/// </summary>
		[DataMember(Order = 12, Name = "GEN.LDGR.INDEX1")]
		public List<string> GenLdgrIndex1 { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.INDEX2
		/// </summary>
		[DataMember(Order = 13, Name = "GEN.LDGR.INDEX2")]
		public List<string> GenLdgrIndex2 { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.INDEX3
		/// </summary>
		[DataMember(Order = 14, Name = "GEN.LDGR.INDEX3")]
		public List<string> GenLdgrIndex3 { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.INDEX4
		/// </summary>
		[DataMember(Order = 15, Name = "GEN.LDGR.INDEX4")]
		public List<string> GenLdgrIndex4 { get; set; }
		
		/// <summary>
		/// CDD Name: GEN.LDGR.STATUS
		/// </summary>
		[DataMember(Order = 16, Name = "GEN.LDGR.STATUS")]
		public string GenLdgrStatus { get; set; }
		
		/// <summary>
		/// Entity assocation member
		/// </summary>
		[DataMember]
		public List<GenLdgrBaseGlflstat> GlflstatEntityAssociation { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			// EntityAssociation Name: GLFLSTAT
			
			GlflstatEntityAssociation = new List<GenLdgrBaseGlflstat>();
			// Set max length to the count of controller when initializing.
			//Update max length if any of the association members has higher length than controller length
			if(GenLdgrFileclass != null)
			{
				int numGlflstat = GenLdgrFileclass.Count;
				if (GenLdgrFname !=null && GenLdgrFname.Count > numGlflstat) numGlflstat = GenLdgrFname.Count;
				if (GenLdgrFilestatus !=null && GenLdgrFilestatus.Count > numGlflstat) numGlflstat = GenLdgrFilestatus.Count;
				if (GenLdgrLocation !=null && GenLdgrLocation.Count > numGlflstat) numGlflstat = GenLdgrLocation.Count;
				if (GenLdgrStatusDate !=null && GenLdgrStatusDate.Count > numGlflstat) numGlflstat = GenLdgrStatusDate.Count;
				if (GenLdgrIndex1 !=null && GenLdgrIndex1.Count > numGlflstat) numGlflstat = GenLdgrIndex1.Count;
				if (GenLdgrIndex2 !=null && GenLdgrIndex2.Count > numGlflstat) numGlflstat = GenLdgrIndex2.Count;
				if (GenLdgrIndex3 !=null && GenLdgrIndex3.Count > numGlflstat) numGlflstat = GenLdgrIndex3.Count;
				if (GenLdgrIndex4 !=null && GenLdgrIndex4.Count > numGlflstat) numGlflstat = GenLdgrIndex4.Count;

				for (int i = 0; i < numGlflstat; i++)
				{

					string value0 = "";
					if (GenLdgrFileclass != null && i < GenLdgrFileclass.Count)
					{
						value0 = GenLdgrFileclass[i];
					}


					string value1 = "";
					if (GenLdgrFname != null && i < GenLdgrFname.Count)
					{
						value1 = GenLdgrFname[i];
					}


					string value2 = "";
					if (GenLdgrFilestatus != null && i < GenLdgrFilestatus.Count)
					{
						value2 = GenLdgrFilestatus[i];
					}


					string value3 = "";
					if (GenLdgrLocation != null && i < GenLdgrLocation.Count)
					{
						value3 = GenLdgrLocation[i];
					}


					DateTime? value4 = null;
					if (GenLdgrStatusDate != null && i < GenLdgrStatusDate.Count)
					{
						value4 = GenLdgrStatusDate[i];
					}


					string value5 = "";
					if (GenLdgrIndex1 != null && i < GenLdgrIndex1.Count)
					{
						value5 = GenLdgrIndex1[i];
					}


					string value6 = "";
					if (GenLdgrIndex2 != null && i < GenLdgrIndex2.Count)
					{
						value6 = GenLdgrIndex2[i];
					}


					string value7 = "";
					if (GenLdgrIndex3 != null && i < GenLdgrIndex3.Count)
					{
						value7 = GenLdgrIndex3[i];
					}


					string value8 = "";
					if (GenLdgrIndex4 != null && i < GenLdgrIndex4.Count)
					{
						value8 = GenLdgrIndex4[i];
					}

					GlflstatEntityAssociation.Add(new GenLdgrBaseGlflstat( value0, value1, value2, value3, value4, value5, value6, value7, value8));
				}
			}
			   
		}
	}
	
	// EntityAssociation classes
	
	[Serializable]
	public class GenLdgrBaseGlflstat
	{
		public string GenLdgrFileclassAssocMember;	
		public string GenLdgrFnameAssocMember;	
		public string GenLdgrFilestatusAssocMember;	
		public string GenLdgrLocationAssocMember;	
		public DateTime? GenLdgrStatusDateAssocMember;	
		public string GenLdgrIndex1AssocMember;	
		public string GenLdgrIndex2AssocMember;	
		public string GenLdgrIndex3AssocMember;	
		public string GenLdgrIndex4AssocMember;	
		public GenLdgrBaseGlflstat() {}
		public GenLdgrBaseGlflstat(
			string inGenLdgrFileclass,
			string inGenLdgrFname,
			string inGenLdgrFilestatus,
			string inGenLdgrLocation,
			DateTime? inGenLdgrStatusDate,
			string inGenLdgrIndex1,
			string inGenLdgrIndex2,
			string inGenLdgrIndex3,
			string inGenLdgrIndex4)
		{
			GenLdgrFileclassAssocMember = inGenLdgrFileclass;
			GenLdgrFnameAssocMember = inGenLdgrFname;
			GenLdgrFilestatusAssocMember = inGenLdgrFilestatus;
			GenLdgrLocationAssocMember = inGenLdgrLocation;
			GenLdgrStatusDateAssocMember = inGenLdgrStatusDate;
			GenLdgrIndex1AssocMember = inGenLdgrIndex1;
			GenLdgrIndex2AssocMember = inGenLdgrIndex2;
			GenLdgrIndex3AssocMember = inGenLdgrIndex3;
			GenLdgrIndex4AssocMember = inGenLdgrIndex4;
		}
	}
}