//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 10:34:07 AM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: HRWEB.DEFAULTS
//     Application: HR
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "HrwebDefaults")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 10:34:07 AM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "HRWEB.DEFAULTS", EntityType = "PERM")]
	public class HrwebDefaults : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: HRWEB.PAY.ADVICE.CHECK.DATE
		/// </summary>
		[DataMember(Order = 23, Name = "HRWEB.PAY.ADVICE.CHECK.DATE")]
		public string HrwebPayAdviceCheckDate { get; set; }
		
		/// <summary>
		/// CDD Name: HRWEB.PAY.ADVICE.PRIOR.YEARS
		/// </summary>
		[DataMember(Order = 32, Name = "HRWEB.PAY.ADVICE.PRIOR.YEARS")]
		public string HrwebPayAdvicePriorYears { get; set; }
		
		/// <summary>
		/// CDD Name: HRWEB.W2O.CON.TEXT
		/// </summary>
		[DataMember(Order = 51, Name = "HRWEB.W2O.CON.TEXT")]
		public string HrwebW2oConText { get; set; }
		
		/// <summary>
		/// CDD Name: HRWEB.W2O.WHLD.TEXT
		/// </summary>
		[DataMember(Order = 54, Name = "HRWEB.W2O.WHLD.TEXT")]
		public string HrwebW2oWhldText { get; set; }
		
		/// <summary>
		/// CDD Name: HRWEB.1095C.CON.TEXT
		/// </summary>
		[DataMember(Order = 59, Name = "HRWEB.1095C.CON.TEXT")]
		public string Hrweb1095cConText { get; set; }
		
		/// <summary>
		/// CDD Name: HRWEB.1095C.WHLD.TEXT
		/// </summary>
		[DataMember(Order = 60, Name = "HRWEB.1095C.WHLD.TEXT")]
		public string Hrweb1095cWhldText { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}