//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 12/9/2019 5:29:06 PM by user balvano3
//
//     Type: ENTITY
//     Entity: INTG.MAPPING.INFO
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "IntgMappingInfo")]
	[ColleagueDataContract(GeneratedDateTime = "12/9/2019 5:29:06 PM", User = "balvano3")]
	[EntityDataContract(EntityName = "INTG.MAPPING.INFO", EntityType = "PHYS")]
	public class IntgMappingInfo : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: IMN.ETHOS.RESOURCE
		/// </summary>
		[DataMember(Order = 0, Name = "IMN.ETHOS.RESOURCE")]
		public string ImnEthosResource { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.ETHOS.PROPERTY.NAME
		/// </summary>
		[DataMember(Order = 1, Name = "IMN.ETHOS.PROPERTY.NAME")]
		public string ImnEthosPropertyName { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.ETHOS.ENUMS.ENTITY
		/// </summary>
		[DataMember(Order = 2, Name = "IMN.ETHOS.ENUMS.ENTITY")]
		public string ImnEthosEnumsEntity { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.ETHOS.ENUMS.VALCODE.ID
		/// </summary>
		[DataMember(Order = 3, Name = "IMN.ETHOS.ENUMS.VALCODE.ID")]
		public string ImnEthosEnumsValcodeId { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.COLL.ENTITY
		/// </summary>
		[DataMember(Order = 4, Name = "IMN.COLL.ENTITY")]
		public string ImnCollEntity { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.COLL.VALCODE.ID
		/// </summary>
		[DataMember(Order = 5, Name = "IMN.COLL.VALCODE.ID")]
		public string ImnCollValcodeId { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.COLL.FIELD.NAME
		/// </summary>
		[DataMember(Order = 6, Name = "IMN.COLL.FIELD.NAME")]
		public string ImnCollFieldName { get; set; }
		
		/// <summary>
		/// CDD Name: IMN.COLL.MAPPING.TITLE
		/// </summary>
		[DataMember(Order = 7, Name = "IMN.COLL.MAPPING.TITLE")]
		public string ImnCollMappingTitle { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}