//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 3/30/2021 1:39:51 PM by user balvano2
//
//     Type: ENTITY
//     Entity: PORTAL.PARAMETERS
//     Application: UT
//     Environment: dvetk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "PortalParameters")]
	[ColleagueDataContract(GeneratedDateTime = "3/30/2021 1:39:51 PM", User = "balvano2")]
	[EntityDataContract(EntityName = "PORTAL.PARAMETERS", EntityType = "LOGI")]
	public class PortalParameters : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: PP.DEFAULT.LEARN.PROVIDER
		/// </summary>
		[DataMember(Order = 55, Name = "")]
		public string PpDefaultLearnProvider { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}