//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/30/2017 10:49:45 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: T4A.CONSENT.HISTORY
//     Application: CF
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "T4aConsentHistory")]
	[ColleagueDataContract(GeneratedDateTime = "10/30/2017 10:49:45 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "T4A.CONSENT.HISTORY", EntityType = "PHYS")]
	public class T4aConsentHistory : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: T4ACH.HRPER.ID
		/// </summary>
		[DataMember(Order = 2, Name = "T4ACH.HRPER.ID")]
		public string T4achHrperId { get; set; }
		
		/// <summary>
		/// CDD Name: T4ACH.NEW.STATUS
		/// </summary>
		[DataMember(Order = 3, Name = "T4ACH.NEW.STATUS")]
		public string T4achNewStatus { get; set; }
		
		/// <summary>
		/// CDD Name: T4A.CONSENT.HISTORY.ADDDATE
		/// </summary>
		[DataMember(Order = 5, Name = "T4A.CONSENT.HISTORY.ADDDATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? T4aConsentHistoryAdddate { get; set; }
		
		/// <summary>
		/// CDD Name: T4A.CONSENT.HISTORY.ADDTIME
		/// </summary>
		[DataMember(Order = 7, Name = "T4A.CONSENT.HISTORY.ADDTIME")]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? T4aConsentHistoryAddtime { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}