//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 10:59:52 AM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: WORKLIST.ADDR
//     Application: UT
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Base.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "WorklistAddr")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 10:59:52 AM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "WORKLIST.ADDR", EntityType = "PHYS")]
	public class WorklistAddr : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: WKLAD.WORKLIST
		/// </summary>
		[DataMember(Order = 0, Name = "WKLAD.WORKLIST")]
		public string WkladWorklist { get; set; }
		
		/// <summary>
		/// CDD Name: WKLAD.ORG.ENTITY
		/// </summary>
		[DataMember(Order = 1, Name = "WKLAD.ORG.ENTITY")]
		public string WkladOrgEntity { get; set; }
		
		/// <summary>
		/// CDD Name: WKLAD.ORG.ROLE
		/// </summary>
		[DataMember(Order = 2, Name = "WKLAD.ORG.ROLE")]
		public string WkladOrgRole { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}