



/* ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the CreateDtoEnum T4 Generator - Version 1.0
//     Last generated on  08/16/2017 09:54:10
//
//      Schema Name:  fiscal-years
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
       Schema definition:         {
                 "title": "Year End Adjustment",
                 "description": "An indication whether the year end adjustment is active or inactive.",
                 "oneOf": [
                   {
                     "type": "string",
                     "enum": [
                       "active",
                       "inactive"
                     ]
                   },
                   {
                     "type": "string",
                     "maxLength": 0
                   }
                 ]
               }  
                       //    // </auto-generated>     
//----------------------------------------------------------------------------- */

// Copyright 2017 Ellucian Company L.P. and its affiliates.

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Runtime.Serialization;


namespace Ellucian.Colleague.Dtos.EnumProperties
{
    /// <summary>
    /// An indication whether the year end adjustment is active or inactive.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FiscalYearsYearEndAdjustment
    {
        /// <summary>
        /// Used when the value is not set or an invalid enumeration is used
        /// </summary>
        NotSet = 0,


        /// <summary>
        /// active
        /// </summary>
        [EnumMember(Value = "active")]
        Active,

        /// <summary>
        /// inactive
        /// </summary>
        [EnumMember(Value = "inactive")]
        Inactive,
    }
}


