//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 2:05:32 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: FA.OUTSIDE.AWARDS
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.FinancialAid.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "FaOutsideAwards")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 2:05:32 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "FA.OUTSIDE.AWARDS", EntityType = "PHYS")]
	public class FaOutsideAwards : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: FOA.YEAR
		/// </summary>
		[DataMember(Order = 0, Name = "FOA.YEAR")]
		public string FoaYear { get; set; }
		
		/// <summary>
		/// CDD Name: FOA.STUDENT.ID
		/// </summary>
		[DataMember(Order = 1, Name = "FOA.STUDENT.ID")]
		public string FoaStudentId { get; set; }
		
		/// <summary>
		/// CDD Name: FOA.AWARD.NAME
		/// </summary>
		[DataMember(Order = 2, Name = "FOA.AWARD.NAME")]
		public string FoaAwardName { get; set; }
		
		/// <summary>
		/// CDD Name: FOA.AMOUNT
		/// </summary>
		[DataMember(Order = 3, Name = "FOA.AMOUNT")]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public Decimal? FoaAmount { get; set; }
		
		/// <summary>
		/// CDD Name: FOA.AWARD.TYPE
		/// </summary>
		[DataMember(Order = 4, Name = "FOA.AWARD.TYPE")]
		public string FoaAwardType { get; set; }
		
		/// <summary>
		/// CDD Name: FOA.FUNDING.SOURCE
		/// </summary>
		[DataMember(Order = 5, Name = "FOA.FUNDING.SOURCE")]
		public string FoaFundingSource { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}