// Copyright 2018 Ellucian Company L.P. and its affiliates.
using Ellucian.Colleague.Data.Base.DataContracts;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Ellucian.Colleague.Data.Base.Tests
{
    public static class TestCountriesRepository
    {
        private static readonly string[,] _allCountries =
{
            {"AA","ARUBA","AW","","ABW"},
            {"AC","ANTIGUA AND BARBUDA","AG","","ATG"},
            {"AF","AFGHANISTAN","AF","","AFG"},
            {"AG","ALGERIA","DZ","","DZA"},
            {"AJ","AZERBAIJAN","AZ","","AZE"},
            {"AL","ALBANIA","AL","","ALB"},
            {"AM","ARMENIA","AM","","ARM"},
            {"AN","ANDORRA","AD","","AND"},
            {"AO","ANGOLA","AO","","AGO"},
            {"AQ","AMERICAN SAMOA","AS","","ASM"},
            {"AR","ARGENTINA","AR","","ARG"},
            {"AS","AUSTRALIA","AU","","AUS"},
            {"AT","ASHMORE AND CARTIER ISLANDS","","",""},
            {"AU","AUSTRIA","AT","","AUT"},
            {"AV","ANGUILLA","AO","","AGO"},
            {"AY","ANTARCTICA","AQ","","ATA"},
            {"BA","BAHRAIN","BH","","BHR"},
            {"BB","BARBADOS","BB","","BRB"},
            {"BC","BOTSWANA","BW","","BWA"},
            {"BD","BERMUDA","BM","","BMU"},
            {"BE","BELGIUM","BE","","BEL"},
            {"BF","BAHAMAS, THE","BS","","BHS"},
            {"BG","BANGLADESH","BD","","BGD"},
            {"BH","BELIZE","BZ","","BLZ"},
            {"BK","BOSNIA AND HERZEGOVINA","BA","","BIH"},
            {"BL","BOLIVIA","","",""},
            {"BM","BURMA   (MYANMAR)","","",""},
            {"BN","BENIN","BJ","","BEN"},
            {"BO","BELARUS","BY","","BLR"},
            {"BP","SOLOMON ISLANDS","SB","","SLB"},
            {"BQ","NAVASSA ISLAND","","",""},
            {"BR","BRAZIL","BR","","BRA"},
            {"BS","BASSAS DA INDIA","","",""},
            {"BT","BHUTAN","BT","","BTN"},
            {"BU","BULGARIA","BG","","BGR"},
            {"BV","BOUVET ISLAND","BV","","BVT"},
            {"BX","BRUNEI","BH","","BHR"},
            {"BY","BURUNDI","BI","","BDI"},
            {"CA","CANADA","CA","","CAN"},
            {"CB","CAMBODIA","KH","","KHM"},
            {"CD","CHAD","TD","","TCD"},
            {"CE","SRI LANKA","LK","","LKA"},
            {"CF","CONGO, REPUBLIC OF THE","","",""},
            {"CG","CONGO, DEMOCRATIC REPUBLIC","","",""},
            {"CH","CHINA","CN","","CHN"},
            {"CI","CHILE","CL","","CHL"},
            {"CJ","CAYMAN ISLANDS","KY","","CYM"},
            {"CK","COCOS (KEELING) ISLANDS","CC","","CCK"},
            {"CM","CAMEROON","CM","","CMR"},
            {"CN","COMOROS","","",""},
            {"CO","COLOMBIA","CO","","COL"},
            {"CQ","NORTHERN MARIANA ISLANDS","MP","","MNP"},
            {"CR","CORAL SEA ISLANDS","","",""},
            {"CS","COSTA RICA","CR","","CRI"},
            {"CT","CENTRAL AFRICAN REPUBLIC","CF","","CAF"},
            {"CU","CUBA","CU","","CUB"},
            {"CV","CAPE VERDE","","",""},
            {"CW","COOK ISLANDS","CK","","COK"},
            {"CY","CYPRUS","CY","","CYP"},
            {"DA","DENMARK","DK","","DNK"},
            {"DJ","DJIBOUTI","DJ","","DJI"},
            {"DO","DOMINICA","DM","","DMA"},
            {"DQ","JARVIS ISLAND","","",""},
            {"DR","DOMINICAN REPUBLIC","DO","","DOM"},
            {"EC","ECUADOR","EC","","ECU"},
            {"EG","EGYPT","EG","","EGY"},
            {"EI","IRELAND","IE","","IRL"},
            {"EK","EQUATORIAL GUINEA","GQ","","GNQ"},
            {"EN","ESTONIA","EE","","EST"},
            {"ER","ERITREA","ER","","ERI"},
            {"ES","EL SALVADOR","SV","","SLV"},
            {"ET","ETHIOPIA","ET","","ETH"},
            {"EU","EUROPA ISLAND","","",""},
            {"EZ","CZECH REPUBLIC","CZ","","CZE"},
            {"FG","FRENCH GUIANA","GF","","GUF"},
            {"FI","FINLAND","FI","","FIN"},
            {"FJ","FIJI","FJ","","FJI"},
            {"FK","FALKLAND ISLANDS","FK","","FLK"},
            {"FM","MICRONESIA","FM","","FSM"},
            {"FO","FAROE ISLANDS","FO","","FRO"},
            {"FP","FRENCH POLYNESIA","PF","","PYF"},
            {"FQ","BAKER ISLAND","","",""},
            {"FR","FRANCE","FR","","FRA"},
            {"FS","FRENCH SOUTHERN ANTARCTICA","TF","","ATF"},
            {"GA","GAMBIA, THE","GM","","GMB"},
            {"GB","GABON","GA","","GAB"},
            {"GG","GEORGIA","GE","","GEO"},
            {"GH","GHANA","GH","","GHA"},
            {"GI","GIBRALTAR","GI","","GIB"},
            {"GJ","GRENADA","GD","","GRD"},
            {"GK","GUERNSEY","GG","","GGY"},
            {"GL","GREENLAND","GL","","GRL"},
            {"GM","GERMANY","DE","","DEU"},
            {"GO","GLORIOSO ISLANDS","","",""},
            {"GP","GUADELOUPE","GP","","GLP"},
            {"GQ","GUAM","GU","","GUM"},
            {"GR","GREECE","GR","","GRC"},
            {"GT","GUATEMALA","GT","","GTM"},
            {"GV","GUINEA","GH","","GHA"},
            {"GY","GUYANA","GY","","GUY"},
            {"GZ","GAZA STRIP","","",""},
            {"HA","HAITI","HT","","HTI"},
            {"HK","HONG KONG","HK","","HKG"},
            {"HM","HEARD MACDONALD ISLANDS","","",""},
            {"HO","HONDURA","","",""},
            {"HQ","HOWLAND ISLAND","","",""},
            {"HR","CROATIA","HR","","HRV"},
            {"HU","HUNGARY","HU","","HUN"},
            {"IC","ICELAND","IS","","ISL"},
            {"ID","INDONESIA","ID","","IDN"},
            {"IM","MAN, ISLE OF","","",""},
            {"IN","INDIA","IN","","IND"},
            {"IO","BRITISH INDIAN OCEAN TERRITORY","IO","","IOT"},
            {"IP","CLIPPERTON ISLAND","","",""},
            {"IR","IRAN","","",""},
            {"IS","ISRAEL","IL","","ISR"},
            {"IT","ITALY","IT","","ITA"},
            {"IV","COTE D IVOIRE","CI","","CIV"},
            {"IZ","IRAQ","IQ","","IRQ"},
            {"JA","JAPAN","JP","","JPN"},
            {"JE","JERSEY","JE","","JEY"},
            {"JM","JAMAICA","JM","","JAM"},
            {"JN","JAN MAYEN","","",""},
            {"JO","JORDAN","JO","","JOR"},
            {"JQ","JOHNSTON ATOLL","","",""},
            {"JU","JUAN DE NOVA ISLAND","","",""},
            {"KE","KENYA","KE","","KEN"},
            {"KG","KYRGYZSTAN","KG","","KGZ"},
            {"KN","KOREA, NORTH","","",""},
            {"KQ","KINGMAN REEF","","",""},
            {"KR","KIRIBATI","KI","","KIR"},
            {"KS","KOREA, SOUTH","","",""},
            {"KT","CHRISTMAS ISLAND","CX","","CXR"},
            {"KU","KUWAIT","KW","","KWT"},
            {"KZ","KAZAKHSTAN","KZ","","KAZ"},
            {"LA","LAOS","","",""},
            {"LE","LEBANON","LB","","LBN"},
            {"LG","LATVIA","LV","","LVA"},
            {"LH","LITHUANIA","LT","","LTU"},
            {"LI","LIBERIA","LR","","LBR"},
            {"LO","SLOVAKIA","SK","","SVK"},
            {"LQ","PALMYRA ATOLL","","",""},
            {"LS","LIECHTENSTEIN","LI","","LIE"},
            {"LT","LESOTHO","LS","","LSO"},
            {"LU","LUXEMBOURG","LU","","LUX"},
            {"LY","LIBYA","LY","","LBY"},
            {"MA","MADAGASCAR","MG","","MDG"},
            {"MB","MARTINIQUE","MQ","","MTQ"},
            {"MC","MACAU","MO","","MAC"},
            {"MD","MOLDOVA","","",""},
            {"MF","MAYOTTE","YT","","MYT"},
            {"MG","MONGOLIA","MN","","MNG"},
            {"MH","MONTSERRAT","MS","","MSR"},
            {"MI","MALAWI","MW","","MWI"},
            {"MK","MACEDONIA, THE REPUBLIC OF","MK","","MKD"},
            {"ML","MALI","ML","","MLI"},
            {"MN","MONACO","MC","","MCO"},
            {"MO","MOROCCO","MA","","MAR"},
            {"MP","MAURITIUS","MU","","MUS"},
            {"MQ","MIDWAY ISLANDS","","",""},
            {"MR","MAURITANIA","MR","","MRT"},
            {"MT","MALTA","MT","","MLT"},
            {"MU","OMAN","OM","","OMN"},
            {"MV","MALDIVES","MV","","MDV"},
            {"MX","MEXICO","MX","","MEX"},
            {"MY","MALAYSIA","MY","","MYS"},
            {"MZ","MOZAMBIQUE","MZ","","MOZ"},
            {"NC","NEW CALEDONIA","NC","","NCL"},
            {"NE","NIUE","NU","","NIU"},
            {"NF","NORFOLK ISLAND","NF","","NFK"},
            {"NG","NIGER","NG","","NGA"},
            {"NH","VANUATU","VU","","VUT"},
            {"NI","NIGERIA","NG","","NGA"},
            {"NL","NETHERLANDS","NL","","NLD"},
            {"NO","NORWAY","NO","","NOR"},
            {"NP","NEPAL","NP","","NPL"},
            {"NR","NAURU","NR","","NRU"},
            {"NS","SURINAME","SR","","SUR"},
            {"NT","NETHERLANDS ANTILLES","NL","","NLD"},
            {"NU","NICARAGUA","NI","","NIC"},
            {"NZ","NEW ZEALAND","NZ","","NZL"},
            {"PA","PARAGUAY","PY","","PRY"},
            {"PC","PITCAIRN ISLANDS","PN","","PCN"},
            {"PE","PERU","PE","","PER"},
            {"PF","PARACEL ISLANDS","","",""},
            {"PG","SPRATLY ISLANDS","","",""},
            {"PK","PAKISTAN","PK","","PAK"},
            {"PL","POLAND","PL","","POL"},
            {"PM","PANAMA","PA","","PAN"},
            {"PO","PORTUGAL","PT","","PRT"},
            {"PP","PAPUA NEW GUINEA","PG","","PNG"},
            {"PS","PALAU","PW","","PLW"},
            {"PU","GUINEA-BISSAU","GW","","GNB"},
            {"QA","QATAR","QA","","QAT"},
            {"RE","REUNION","RE","","REU"},
            {"RM","MARSHALL ISLANDS","MH","","MHL"},
            {"RO","ROMANIA","RO","","ROU"},
            {"RP","PHILIPPINES","PH","","PHL"},
            {"RQ","PUERTO RICO","PR","","PRI"},
            {"RS","RUSSIA","","",""},
            {"RW","RWANDA","RW","","RWA"},
            {"SA","SAUDI ARABIA","SA","","SAU"},
            {"SB","SAINT PIERRE AND MIQUELON","PM","","SPM"},
            {"SC","SAINT KITTS AND NEVIS","KN","","KNA"},
            {"SE","SEYCHELLES","SC","","SYC"},
            {"SF","SOUTH AFRICA","ZA","","ZAF"},
            {"SG","SENEGAL","SN","","SEN"},
            {"SH","SAINT HELENA","SH","","SHN"},
            {"SI","SLOVENIA","SI","","SVN"},
            {"SL","SIERRA LEONE","SL","","SLE"},
            {"SM","SAN MARINO","SM","","SMR"},
            {"SN","SINGAPORE","SG","","SGP"},
            {"SO","SOMALIA","SO","","SOM"},
            {"SP","SPAIN","ES","","ESP"},
            {"ST","SAINT LUCIA","LC","","LCA"},
            {"SU","SUDAN","","",""},
            {"SV","SVALBARD","SJ","","SJM"},
            {"SW","SWEDEN","SE","","SWE"},
            {"SX","S GEORGIA S SANDWICH ISLANDS","","",""},
            {"SY","SYRIA","","",""},
            {"SZ","SWITZERLAND","CH","","CHE"},
            {"TC","UNITED ARAB EMIRATES","AE","","ARE"},
            {"TD","TRINIDAD AND TOBAGO","TT","","TTO"},
            {"TE","TROMELIN ISLAND","","",""},
            {"TH","THAILAND","TH","","THA"},
            {"TI","TAJIKISTAN","TJ","","TJK"},
            {"TK","TURKS AND CAICOS ISLANDS","TC","","TCA"},
            {"TL","TOKELAU","TK","","TKL"},
            {"TN","TONGA","TO","","TON"},
            {"TO","TOGO","TG","","TGO"},
            {"TP","SAO TOME AND PRINCIPE","ST","","STP"},
            {"TS","TUNISIA","TN","","TUN"},
            {"TT","EAST TIMOR","","",""},
            {"TU","TURKEY","TR","","TUR"},
            {"TV","TUVALU","TV","","TUV"},
            {"TW","TAIWAN","","",""},
            {"TX","TURKMENISTAN","TM","","TKM"},
            {"TZ","TANZANIA","","",""},
            {"U1","CZECHOSLOVAKIA","","",""},
            {"U2","NEUTRAL ZONE","","",""},
            {"U3","STATELESS","","",""},
            {"U4","USSR","","",""},
            {"U5","UNKNOWN","","",""},
            {"UG","UGANDA","UG","","UGA"},
            {"UK","UNITED KINGDOM","GB","","GBR"},
            {"UP","UKRAINE","UA","","UKR"},
            {"US","UNITED STATES","US","","USA"},
            {"UV","BURKINA FASO","BF","","BFA"},
            {"UY","URUGUAY","UY","","URY"},
            {"UZ","UZBEKISTAN","UZ","","UZB"},
            {"VC","ST VINCENT THE GRENADINES","","",""},
            {"VE","VENEZUELA","","",""},
            {"VI","BRITISH VIRGIN ISLANDS","","",""},
            {"VM","VIETNAM","VN","","VNM"},
            {"VQ","U.S. VIRGIN ISLANDS","","",""},
            {"VT","VATICAN CITY   (HOLY SEE)","","",""},
            {"WA","NAMIBIA","NA","","NAM"},
            {"WE","WEST BANK","","",""},
            {"WF","WALLIS AND FUTUNA","WF","","WLF"},
            {"WI","WESTERN SAHARA","EH","","ESH"},
            {"WQ","WAKE ISLAND","","",""},
            {"WS","SAMOA   (WESTERN SAMOA)","","",""},
            {"WZ","SWAZILAND","SZ","","SWZ"},
            {"YI","YUGOSLAVIA","","",""},
            {"YM","YEMEN","YE","","YEM"},
            {"ZA","ZAMBIA","ZM","","ZMB"},
            {"ZI","ZIMBABWE","ZW","","ZWE"}
        };

        /// <summary>
        /// Gets all COUNTRIES records
        /// </summary>
        /// <returns>All COUNTRIES records</returns>
        public static IEnumerable<Countries> GetAllCountriesRecords()
        {
            var countryList = new List<Countries>();
            var items = _allCountries.Length / 5;
            for (var x = 0; x < items; x++)
            {
                try
                {
                    countryList.Add(new Countries() {
                        Recordkey = _allCountries[x, 0],
                        CtryDesc = _allCountries[x, 1],
                        CtryIsoCode = _allCountries[x, 2],
                        CtryIsoAlpha3Code = _allCountries[x, 3],
                        CtryNotInUseFlag = _allCountries[x, 4].ToUpperInvariant(),
                        RecordGuid = Guid.NewGuid().ToString()
                    });
                }
                catch (Exception) { }
            }
            return countryList.AsEnumerable();
        }

    }
}
