//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 7/31/2022 4:57:13 PM by user nravioli
//
//     Type: CTX
//     Transaction ID: GET.FA.PROGRAM
//     Application: ST
//     Environment: DVColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.FinancialAid.Transactions
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.FA.PROGRAM", GeneratedDateTime = "7/31/2022 4:57:13 PM", User = "nravioli")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class GetFaProgramRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "AWARD.PERIOD.ID", InBoundData = true)]        
		public string AwardPeriodId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "STUDENT.ID", InBoundData = true)]        
		public string StudentId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "AWARD.YEAR", InBoundData = true)]        
		public string AwardYear { get; set; }

		public GetFaProgramRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.FA.PROGRAM", GeneratedDateTime = "7/31/2022 4:57:13 PM", User = "nravioli")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class GetFaProgramResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "PROGRAM.NAME", OutBoundData = true)]        
		public string ProgramName { get; set; }

		public GetFaProgramResponse()
		{	
		}
	}
}
