//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/27/2017 11:11:55 AM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: PER.ASGMT.CONTRACT
//     Application: HR
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.HumanResources.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "PerAsgmtContract")]
	[ColleagueDataContract(GeneratedDateTime = "10/27/2017 11:11:55 AM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "PER.ASGMT.CONTRACT", EntityType = "PHYS")]
	public class PerAsgmtContract : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: PAC.DESC
		/// </summary>
		[DataMember(Order = 0, Name = "PAC.DESC")]
		public string PacDesc { get; set; }
		
		/// <summary>
		/// CDD Name: PAC.HRP.ID
		/// </summary>
		[DataMember(Order = 1, Name = "PAC.HRP.ID")]
		public string PacHrpId { get; set; }
		
		/// <summary>
		/// CDD Name: PAC.NO
		/// </summary>
		[DataMember(Order = 2, Name = "PAC.NO")]
		public string PacNo { get; set; }
		
		/// <summary>
		/// CDD Name: PAC.TYPE
		/// </summary>
		[DataMember(Order = 3, Name = "PAC.TYPE")]
		public string PacType { get; set; }
		
		/// <summary>
		/// CDD Name: PAC.START.DATE
		/// </summary>
		[DataMember(Order = 5, Name = "PAC.START.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? PacStartDate { get; set; }
		
		/// <summary>
		/// CDD Name: PAC.END.DATE
		/// </summary>
		[DataMember(Order = 6, Name = "PAC.END.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? PacEndDate { get; set; }
		
		/// <summary>
		/// CDD Name: PAC.ALL.LOAD.PERIODS
		/// </summary>
		[DataMember(Order = 13, Name = "PAC.ALL.LOAD.PERIODS")]
		public List<string> PacAllLoadPeriods { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}