//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 2:32:25 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: SWTABLES
//     Application: HR
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.HumanResources.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "Swtables")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 2:32:25 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "SWTABLES", EntityType = "PHYS")]
	public class Swtables : IColleagueGuidEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
	
		/// <summary>
		/// Record GUID
		/// </summary>
		[DataMember(Name = "RecordGuid")]
		public string RecordGuid { get; set; }

		/// <summary>
		/// Record Model Name
		/// </summary>
		[DataMember(Name = "RecordModelName")]
		public string RecordModelName { get; set; }	
		
		/// <summary>
		/// CDD Name: SWT.DESC
		/// </summary>
		[DataMember(Order = 0, Name = "SWT.DESC")]
		public string SwtDesc { get; set; }
		
		/// <summary>
		/// CDD Name: SWT.STATUS
		/// </summary>
		[DataMember(Order = 2, Name = "SWT.STATUS")]
		public string SwtStatus { get; set; }
		
		/// <summary>
		/// CDD Name: SWT.TYPE
		/// </summary>
		[DataMember(Order = 5, Name = "SWT.TYPE")]
		public string SwtType { get; set; }
		
		/// <summary>
		/// CDD Name: SWT.HRLY.OR.SLRY
		/// </summary>
		[DataMember(Order = 6, Name = "SWT.HRLY.OR.SLRY")]
		public string SwtHrlyOrSlry { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}