//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 4/28/2020 9:50:21 AM by user gtt_dvcoll_wstst01
//
//     Type: ENTITY
//     Entity: WEB.T4.ONLINE
//     Application: HR
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.HumanResources.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "WebT4Online")]
	[ColleagueDataContract(GeneratedDateTime = "4/28/2020 9:50:21 AM", User = "gtt_dvcoll_wstst01")]
	[EntityDataContract(EntityName = "WEB.T4.ONLINE", EntityType = "PHYS")]
	public class WebT4Online : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: WT4O.YEAR
		/// </summary>
		[DataMember(Order = 0, Name = "WT4O.YEAR")]
		public string Wt4oYear { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.SURNAME
		/// </summary>
		[DataMember(Order = 2, Name = "WT4O.SURNAME")]
		public string Wt4oSurname { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.FIRST.NAME
		/// </summary>
		[DataMember(Order = 3, Name = "WT4O.FIRST.NAME")]
		public string Wt4oFirstName { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.INITIAL
		/// </summary>
		[DataMember(Order = 4, Name = "WT4O.INITIAL")]
		public string Wt4oInitial { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.ADDR1
		/// </summary>
		[DataMember(Order = 5, Name = "WT4O.ADDR1")]
		public string Wt4oAddr1 { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.ADDR2
		/// </summary>
		[DataMember(Order = 6, Name = "WT4O.ADDR2")]
		public string Wt4oAddr2 { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.CITY
		/// </summary>
		[DataMember(Order = 7, Name = "WT4O.CITY")]
		public string Wt4oCity { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PROVINCE.CODE
		/// </summary>
		[DataMember(Order = 8, Name = "WT4O.PROVINCE.CODE")]
		public string Wt4oProvinceCode { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.COUNTRY.CODE
		/// </summary>
		[DataMember(Order = 9, Name = "WT4O.COUNTRY.CODE")]
		public string Wt4oCountryCode { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.POSTAL.CODE
		/// </summary>
		[DataMember(Order = 10, Name = "WT4O.POSTAL.CODE")]
		public string Wt4oPostalCode { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.SIN
		/// </summary>
		[DataMember(Order = 11, Name = "WT4O.SIN")]
		public string Wt4oSin { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PENSION.RGST.NO
		/// </summary>
		[DataMember(Order = 15, Name = "WT4O.PENSION.RGST.NO")]
		public List<string> Wt4oPensionRgstNo { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.BOX.CODES
		/// </summary>
		[DataMember(Order = 16, Name = "WT4O.BOX.CODES")]
		public List<string> Wt4oBoxCodes { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.BOX.FN.AMT
		/// </summary>
		[DataMember(Order = 17, Name = "WT4O.BOX.FN.AMT")]
		public List<string> Wt4oBoxFnAmt { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.FORM.TEXT
		/// </summary>
		[DataMember(Order = 18, Name = "WT4O.FORM.TEXT")]
		public List<string> Wt4oFormText { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.EMPLOYEE.ID
		/// </summary>
		[DataMember(Order = 20, Name = "WT4O.EMPLOYEE.ID")]
		public string Wt4oEmployeeId { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.EI.EXEMPT
		/// </summary>
		[DataMember(Order = 21, Name = "WT4O.EI.EXEMPT")]
		public string Wt4oEiExempt { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.CPP.EXEMPT
		/// </summary>
		[DataMember(Order = 22, Name = "WT4O.CPP.EXEMPT")]
		public string Wt4oCppExempt { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.EMPLOYMENT.CODE
		/// </summary>
		[DataMember(Order = 24, Name = "WT4O.EMPLOYMENT.CODE")]
		public string Wt4oEmploymentCode { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.EMPLOYMENT.PROVINCE
		/// </summary>
		[DataMember(Order = 25, Name = "WT4O.EMPLOYMENT.PROVINCE")]
		public string Wt4oEmploymentProvince { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.OTHER.INFO.FLAGS
		/// </summary>
		[DataMember(Order = 26, Name = "WT4O.OTHER.INFO.FLAGS")]
		public List<string> Wt4oOtherInfoFlags { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.NAME1
		/// </summary>
		[DataMember(Order = 27, Name = "WT4O.PAYER.NAME1")]
		public string Wt4oPayerName1 { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.NAME2
		/// </summary>
		[DataMember(Order = 28, Name = "WT4O.PAYER.NAME2")]
		public string Wt4oPayerName2 { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.PROV.CODE
		/// </summary>
		[DataMember(Order = 29, Name = "WT4O.PAYER.PROV.CODE")]
		public string Wt4oPayerProvCode { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PPIP.EXEMPT
		/// </summary>
		[DataMember(Order = 30, Name = "WT4O.PPIP.EXEMPT")]
		public string Wt4oPpipExempt { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.ADDR1
		/// </summary>
		[DataMember(Order = 33, Name = "WT4O.PAYER.ADDR1")]
		public string Wt4oPayerAddr1 { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.ADDR2
		/// </summary>
		[DataMember(Order = 34, Name = "WT4O.PAYER.ADDR2")]
		public string Wt4oPayerAddr2 { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.CITY
		/// </summary>
		[DataMember(Order = 35, Name = "WT4O.PAYER.CITY")]
		public string Wt4oPayerCity { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.POSTAL.CODE
		/// </summary>
		[DataMember(Order = 36, Name = "WT4O.PAYER.POSTAL.CODE")]
		public string Wt4oPayerPostalCode { get; set; }
		
		/// <summary>
		/// CDD Name: WT4O.PAYER.COUNTRY
		/// </summary>
		[DataMember(Order = 37, Name = "WT4O.PAYER.COUNTRY")]
		public string Wt4oPayerCountry { get; set; }
		
		/// <summary>
		/// CDD Name: WEB.T4.ONLINE.ADDDATE
		/// </summary>
		[DataMember(Order = 39, Name = "WEB.T4.ONLINE.ADDDATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? WebT4OnlineAdddate { get; set; }
		
		/// <summary>
		/// CDD Name: WEB.T4.ONLINE.ADDTIME
		/// </summary>
		[DataMember(Order = 41, Name = "WEB.T4.ONLINE.ADDTIME")]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? WebT4OnlineAddtime { get; set; }
		
		/// <summary>
		/// Entity assocation member
		/// </summary>
		[DataMember]
		public List<WebT4OnlineT4BoxInformation> T4BoxInformationEntityAssociation { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			// EntityAssociation Name: T4.BOX.INFORMATION
			
			T4BoxInformationEntityAssociation = new List<WebT4OnlineT4BoxInformation>();
			// Set max length to the count of controller when initializing.
			//Update max length if any of the association members has higher length than controller length
			if(Wt4oBoxCodes != null)
			{
				int numT4BoxInformation = Wt4oBoxCodes.Count;
				if (Wt4oBoxFnAmt !=null && Wt4oBoxFnAmt.Count > numT4BoxInformation) numT4BoxInformation = Wt4oBoxFnAmt.Count;
				if (Wt4oOtherInfoFlags !=null && Wt4oOtherInfoFlags.Count > numT4BoxInformation) numT4BoxInformation = Wt4oOtherInfoFlags.Count;

				for (int i = 0; i < numT4BoxInformation; i++)
				{

					string value0 = "";
					if (Wt4oBoxCodes != null && i < Wt4oBoxCodes.Count)
					{
						value0 = Wt4oBoxCodes[i];
					}


					string value1 = "";
					if (Wt4oBoxFnAmt != null && i < Wt4oBoxFnAmt.Count)
					{
						value1 = Wt4oBoxFnAmt[i];
					}


					string value2 = "";
					if (Wt4oOtherInfoFlags != null && i < Wt4oOtherInfoFlags.Count)
					{
						value2 = Wt4oOtherInfoFlags[i];
					}

					T4BoxInformationEntityAssociation.Add(new WebT4OnlineT4BoxInformation( value0, value1, value2));
				}
			}
			   
		}
	}
	
	// EntityAssociation classes
	
	[Serializable]
	public class WebT4OnlineT4BoxInformation
	{
		public string Wt4oBoxCodesAssocMember;	
		public string Wt4oBoxFnAmtAssocMember;	
		public string Wt4oOtherInfoFlagsAssocMember;	
		public WebT4OnlineT4BoxInformation() {}
		public WebT4OnlineT4BoxInformation(
			string inWt4oBoxCodes,
			string inWt4oBoxFnAmt,
			string inWt4oOtherInfoFlags)
		{
			Wt4oBoxCodesAssocMember = inWt4oBoxCodes;
			Wt4oBoxFnAmtAssocMember = inWt4oBoxFnAmt;
			Wt4oOtherInfoFlagsAssocMember = inWt4oOtherInfoFlags;
		}
	}
}