//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 2:34:18 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: WEB.W2.ONLINE
//     Application: HR
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.HumanResources.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "WebW2Online")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 2:34:18 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "WEB.W2.ONLINE", EntityType = "PHYS")]
	public class WebW2Online : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: WW2O.EMPLOYEE.ID
		/// </summary>
		[DataMember(Order = 0, Name = "WW2O.EMPLOYEE.ID")]
		public string Ww2oEmployeeId { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.YEAR
		/// </summary>
		[DataMember(Order = 1, Name = "WW2O.YEAR")]
		public string Ww2oYear { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYR.ID
		/// </summary>
		[DataMember(Order = 4, Name = "WW2O.EMPLYR.ID")]
		public string Ww2oEmplyrId { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYR.NAME
		/// </summary>
		[DataMember(Order = 5, Name = "WW2O.EMPLYR.NAME")]
		public string Ww2oEmplyrName { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYR.ADDR.LINE1
		/// </summary>
		[DataMember(Order = 6, Name = "WW2O.EMPLYR.ADDR.LINE1")]
		public string Ww2oEmplyrAddrLine1 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYR.ADDR.LINE2
		/// </summary>
		[DataMember(Order = 7, Name = "WW2O.EMPLYR.ADDR.LINE2")]
		public string Ww2oEmplyrAddrLine2 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYR.ADDR.LINE3
		/// </summary>
		[DataMember(Order = 8, Name = "WW2O.EMPLYR.ADDR.LINE3")]
		public string Ww2oEmplyrAddrLine3 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYR.ADDR.LINE4
		/// </summary>
		[DataMember(Order = 9, Name = "WW2O.EMPLYR.ADDR.LINE4")]
		public string Ww2oEmplyrAddrLine4 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.SSN
		/// </summary>
		[DataMember(Order = 10, Name = "WW2O.SSN")]
		public string Ww2oSsn { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.FIRST.NAME
		/// </summary>
		[DataMember(Order = 11, Name = "WW2O.FIRST.NAME")]
		public string Ww2oFirstName { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.MIDDLE.NAME
		/// </summary>
		[DataMember(Order = 12, Name = "WW2O.MIDDLE.NAME")]
		public string Ww2oMiddleName { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LAST.NAME
		/// </summary>
		[DataMember(Order = 13, Name = "WW2O.LAST.NAME")]
		public string Ww2oLastName { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYE.ADDR.LINE1
		/// </summary>
		[DataMember(Order = 14, Name = "WW2O.EMPLYE.ADDR.LINE1")]
		public string Ww2oEmplyeAddrLine1 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYE.ADDR.LINE2
		/// </summary>
		[DataMember(Order = 15, Name = "WW2O.EMPLYE.ADDR.LINE2")]
		public string Ww2oEmplyeAddrLine2 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYE.ADDR.LINE3
		/// </summary>
		[DataMember(Order = 16, Name = "WW2O.EMPLYE.ADDR.LINE3")]
		public string Ww2oEmplyeAddrLine3 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYE.ADDR.LINE4
		/// </summary>
		[DataMember(Order = 17, Name = "WW2O.EMPLYE.ADDR.LINE4")]
		public string Ww2oEmplyeAddrLine4 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYE.ADDR.LINE5
		/// </summary>
		[DataMember(Order = 18, Name = "WW2O.EMPLYE.ADDR.LINE5")]
		public string Ww2oEmplyeAddrLine5 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.EMPLYE.ADDR.LINE6
		/// </summary>
		[DataMember(Order = 19, Name = "WW2O.EMPLYE.ADDR.LINE6")]
		public string Ww2oEmplyeAddrLine6 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.FEDERAL.WAGES
		/// </summary>
		[DataMember(Order = 20, Name = "WW2O.FEDERAL.WAGES")]
		public string Ww2oFederalWages { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.FEDERAL.WITHHOLDING
		/// </summary>
		[DataMember(Order = 21, Name = "WW2O.FEDERAL.WITHHOLDING")]
		public string Ww2oFederalWithholding { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.SOC.SEC.WAGES
		/// </summary>
		[DataMember(Order = 22, Name = "WW2O.SOC.SEC.WAGES")]
		public string Ww2oSocSecWages { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.SOC.SEC.WITHHOLDING
		/// </summary>
		[DataMember(Order = 23, Name = "WW2O.SOC.SEC.WITHHOLDING")]
		public string Ww2oSocSecWithholding { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.MEDICARE.WAGES
		/// </summary>
		[DataMember(Order = 24, Name = "WW2O.MEDICARE.WAGES")]
		public string Ww2oMedicareWages { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.MEDICARE.WITHHOLDING
		/// </summary>
		[DataMember(Order = 25, Name = "WW2O.MEDICARE.WITHHOLDING")]
		public string Ww2oMedicareWithholding { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.SOC.SEC.TIPS
		/// </summary>
		[DataMember(Order = 26, Name = "WW2O.SOC.SEC.TIPS")]
		public string Ww2oSocSecTips { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.ALLOCATED.TIPS
		/// </summary>
		[DataMember(Order = 27, Name = "WW2O.ALLOCATED.TIPS")]
		public string Ww2oAllocatedTips { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.ADVANCE.EIC
		/// </summary>
		[DataMember(Order = 28, Name = "WW2O.ADVANCE.EIC")]
		public string Ww2oAdvanceEic { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.DEPENDENT.CARE
		/// </summary>
		[DataMember(Order = 29, Name = "WW2O.DEPENDENT.CARE")]
		public string Ww2oDependentCare { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.NONQUAL.TOTAL
		/// </summary>
		[DataMember(Order = 31, Name = "WW2O.NONQUAL.TOTAL")]
		public string Ww2oNonqualTotal { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.CODE.A
		/// </summary>
		[DataMember(Order = 33, Name = "WW2O.CODE.BOX.CODE.A")]
		public string Ww2oCodeBoxCodeA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.AMOUNT.A
		/// </summary>
		[DataMember(Order = 34, Name = "WW2O.CODE.BOX.AMOUNT.A")]
		public string Ww2oCodeBoxAmountA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.CODE.B
		/// </summary>
		[DataMember(Order = 35, Name = "WW2O.CODE.BOX.CODE.B")]
		public string Ww2oCodeBoxCodeB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.AMOUNT.B
		/// </summary>
		[DataMember(Order = 36, Name = "WW2O.CODE.BOX.AMOUNT.B")]
		public string Ww2oCodeBoxAmountB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.CODE.C
		/// </summary>
		[DataMember(Order = 37, Name = "WW2O.CODE.BOX.CODE.C")]
		public string Ww2oCodeBoxCodeC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.AMOUNT.C
		/// </summary>
		[DataMember(Order = 38, Name = "WW2O.CODE.BOX.AMOUNT.C")]
		public string Ww2oCodeBoxAmountC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.CODE.D
		/// </summary>
		[DataMember(Order = 39, Name = "WW2O.CODE.BOX.CODE.D")]
		public string Ww2oCodeBoxCodeD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.AMOUNT.D
		/// </summary>
		[DataMember(Order = 40, Name = "WW2O.CODE.BOX.AMOUNT.D")]
		public string Ww2oCodeBoxAmountD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.CODE.E
		/// </summary>
		[DataMember(Order = 41, Name = "WW2O.CODE.BOX.CODE.E")]
		public string Ww2oCodeBoxCodeE { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.AMOUNT.E
		/// </summary>
		[DataMember(Order = 42, Name = "WW2O.CODE.BOX.AMOUNT.E")]
		public string Ww2oCodeBoxAmountE { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.CODE.F
		/// </summary>
		[DataMember(Order = 43, Name = "WW2O.CODE.BOX.CODE.F")]
		public string Ww2oCodeBoxCodeF { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CODE.BOX.AMOUNT.F
		/// </summary>
		[DataMember(Order = 44, Name = "WW2O.CODE.BOX.AMOUNT.F")]
		public string Ww2oCodeBoxAmountF { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.CODE.A
		/// </summary>
		[DataMember(Order = 45, Name = "WW2O.OTHER.BOX.CODE.A")]
		public string Ww2oOtherBoxCodeA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.AMOUNT.A
		/// </summary>
		[DataMember(Order = 46, Name = "WW2O.OTHER.BOX.AMOUNT.A")]
		public string Ww2oOtherBoxAmountA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.CODE.B
		/// </summary>
		[DataMember(Order = 47, Name = "WW2O.OTHER.BOX.CODE.B")]
		public string Ww2oOtherBoxCodeB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.AMOUNT.B
		/// </summary>
		[DataMember(Order = 48, Name = "WW2O.OTHER.BOX.AMOUNT.B")]
		public string Ww2oOtherBoxAmountB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.CODE.C
		/// </summary>
		[DataMember(Order = 49, Name = "WW2O.OTHER.BOX.CODE.C")]
		public string Ww2oOtherBoxCodeC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.AMOUNT.C
		/// </summary>
		[DataMember(Order = 50, Name = "WW2O.OTHER.BOX.AMOUNT.C")]
		public string Ww2oOtherBoxAmountC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.CODE.D
		/// </summary>
		[DataMember(Order = 51, Name = "WW2O.OTHER.BOX.CODE.D")]
		public string Ww2oOtherBoxCodeD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.AMOUNT.D
		/// </summary>
		[DataMember(Order = 52, Name = "WW2O.OTHER.BOX.AMOUNT.D")]
		public string Ww2oOtherBoxAmountD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.CODE.E
		/// </summary>
		[DataMember(Order = 53, Name = "WW2O.OTHER.BOX.CODE.E")]
		public string Ww2oOtherBoxCodeE { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.AMOUNT.E
		/// </summary>
		[DataMember(Order = 54, Name = "WW2O.OTHER.BOX.AMOUNT.E")]
		public string Ww2oOtherBoxAmountE { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.CODE.F
		/// </summary>
		[DataMember(Order = 55, Name = "WW2O.OTHER.BOX.CODE.F")]
		public string Ww2oOtherBoxCodeF { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.OTHER.BOX.AMOUNT.F
		/// </summary>
		[DataMember(Order = 56, Name = "WW2O.OTHER.BOX.AMOUNT.F")]
		public string Ww2oOtherBoxAmountF { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CHECK.BOX.1
		/// </summary>
		[DataMember(Order = 57, Name = "WW2O.CHECK.BOX.1")]
		public string Ww2oCheckBox1 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CHECK.BOX.3
		/// </summary>
		[DataMember(Order = 59, Name = "WW2O.CHECK.BOX.3")]
		public string Ww2oCheckBox3 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.CHECK.BOX.6
		/// </summary>
		[DataMember(Order = 62, Name = "WW2O.CHECK.BOX.6")]
		public string Ww2oCheckBox6 { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.CODE.A
		/// </summary>
		[DataMember(Order = 63, Name = "WW2O.STATE.CODE.A")]
		public string Ww2oStateCodeA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.ID.A
		/// </summary>
		[DataMember(Order = 64, Name = "WW2O.STATE.ID.A")]
		public string Ww2oStateIdA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WAGES.A
		/// </summary>
		[DataMember(Order = 65, Name = "WW2O.STATE.WAGES.A")]
		public string Ww2oStateWagesA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WITHHELD.A
		/// </summary>
		[DataMember(Order = 66, Name = "WW2O.STATE.WITHHELD.A")]
		public string Ww2oStateWithheldA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.CODE.B
		/// </summary>
		[DataMember(Order = 67, Name = "WW2O.STATE.CODE.B")]
		public string Ww2oStateCodeB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.ID.B
		/// </summary>
		[DataMember(Order = 68, Name = "WW2O.STATE.ID.B")]
		public string Ww2oStateIdB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WAGES.B
		/// </summary>
		[DataMember(Order = 69, Name = "WW2O.STATE.WAGES.B")]
		public string Ww2oStateWagesB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WITHHELD.B
		/// </summary>
		[DataMember(Order = 70, Name = "WW2O.STATE.WITHHELD.B")]
		public string Ww2oStateWithheldB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.CODE.C
		/// </summary>
		[DataMember(Order = 71, Name = "WW2O.STATE.CODE.C")]
		public string Ww2oStateCodeC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.ID.C
		/// </summary>
		[DataMember(Order = 72, Name = "WW2O.STATE.ID.C")]
		public string Ww2oStateIdC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WAGES.C
		/// </summary>
		[DataMember(Order = 73, Name = "WW2O.STATE.WAGES.C")]
		public string Ww2oStateWagesC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WITHHELD.C
		/// </summary>
		[DataMember(Order = 74, Name = "WW2O.STATE.WITHHELD.C")]
		public string Ww2oStateWithheldC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.CODE.D
		/// </summary>
		[DataMember(Order = 75, Name = "WW2O.STATE.CODE.D")]
		public string Ww2oStateCodeD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.ID.D
		/// </summary>
		[DataMember(Order = 76, Name = "WW2O.STATE.ID.D")]
		public string Ww2oStateIdD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WAGES.D
		/// </summary>
		[DataMember(Order = 77, Name = "WW2O.STATE.WAGES.D")]
		public string Ww2oStateWagesD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.STATE.WITHHELD.D
		/// </summary>
		[DataMember(Order = 78, Name = "WW2O.STATE.WITHHELD.D")]
		public string Ww2oStateWithheldD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.NAME.A
		/// </summary>
		[DataMember(Order = 79, Name = "WW2O.LOCAL.NAME.A")]
		public string Ww2oLocalNameA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WAGES.A
		/// </summary>
		[DataMember(Order = 80, Name = "WW2O.LOCAL.WAGES.A")]
		public string Ww2oLocalWagesA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WITHHELD.A
		/// </summary>
		[DataMember(Order = 81, Name = "WW2O.LOCAL.WITHHELD.A")]
		public string Ww2oLocalWithheldA { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.NAME.B
		/// </summary>
		[DataMember(Order = 82, Name = "WW2O.LOCAL.NAME.B")]
		public string Ww2oLocalNameB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WAGES.B
		/// </summary>
		[DataMember(Order = 83, Name = "WW2O.LOCAL.WAGES.B")]
		public string Ww2oLocalWagesB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WITHHELD.B
		/// </summary>
		[DataMember(Order = 84, Name = "WW2O.LOCAL.WITHHELD.B")]
		public string Ww2oLocalWithheldB { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.NAME.C
		/// </summary>
		[DataMember(Order = 85, Name = "WW2O.LOCAL.NAME.C")]
		public string Ww2oLocalNameC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WAGES.C
		/// </summary>
		[DataMember(Order = 86, Name = "WW2O.LOCAL.WAGES.C")]
		public string Ww2oLocalWagesC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WITHHELD.C
		/// </summary>
		[DataMember(Order = 87, Name = "WW2O.LOCAL.WITHHELD.C")]
		public string Ww2oLocalWithheldC { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.NAME.D
		/// </summary>
		[DataMember(Order = 88, Name = "WW2O.LOCAL.NAME.D")]
		public string Ww2oLocalNameD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WAGES.D
		/// </summary>
		[DataMember(Order = 89, Name = "WW2O.LOCAL.WAGES.D")]
		public string Ww2oLocalWagesD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.LOCAL.WITHHELD.D
		/// </summary>
		[DataMember(Order = 90, Name = "WW2O.LOCAL.WITHHELD.D")]
		public string Ww2oLocalWithheldD { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.W2C.FLAG
		/// </summary>
		[DataMember(Order = 96, Name = "WW2O.W2C.FLAG")]
		public string Ww2oW2cFlag { get; set; }
		
		/// <summary>
		/// CDD Name: WW2O.SUFFIX
		/// </summary>
		[DataMember(Order = 101, Name = "WW2O.SUFFIX")]
		public string Ww2oSuffix { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}