//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 11/18/2019 02:28:32 PM by user ganeshrajan
//
//     Type: CTX
//     Transaction ID: CREATE.LEAVE.REQUEST
//     Application: HR
//     Environment: Colleage Studio Dev
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.HumanResources.Transactions
{
	[DataContract]
	public class CreateLeaveRequestDetails
	{
		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "IN.LRD.LEAVE.DATE", InBoundData = true)]
		public Nullable<DateTime> LrdLeaveDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "IN.LRD.LEAVE.HOURS", InBoundData = true)]
		public Nullable<Decimal> LrdHours { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "CREATE.LEAVE.REQUEST", GeneratedDateTime = "11/18/2019 02:28:32 PM", User = "ganeshrajan")]
	[SctrqDataContract(Application = "HR", DataContractVersion = 1)]
	public class CreateLeaveRequestRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "IN.LR.EMPLOYEE.ID", InBoundData = true)]        
		public string LrEmployeeId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "IN.LR.PERLEAVE.ID", InBoundData = true)]        
		public string LrPerleaveId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "IN.LR.START.DATE", InBoundData = true)]        
		public Nullable<DateTime> LrStartDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "IN.LR.END.DATE", InBoundData = true)]        
		public Nullable<DateTime> LrEndDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "IN.LR.APPROVER.ID", InBoundData = true)]        
		public string LrApproverId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "IN.LR.APPROVER.NAME", InBoundData = true)]        
		public string LrApproverName { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:IN.LRD.LEAVE.HOURS", InBoundData = true)]
		public List<CreateLeaveRequestDetails> CreateLeaveRequestDetails { get; set; }

		public CreateLeaveRequestRequest()
		{	
			CreateLeaveRequestDetails = new List<CreateLeaveRequestDetails>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "CREATE.LEAVE.REQUEST", GeneratedDateTime = "11/18/2019 02:28:32 PM", User = "ganeshrajan")]
	[SctrqDataContract(Application = "HR", DataContractVersion = 1)]
	public class CreateLeaveRequestResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGE", OutBoundData = true)]        
		public string ErrorMessage { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.LEAVE.REQUEST.ID", OutBoundData = true)]        
		public string OutLeaveRequestId { get; set; }

		public CreateLeaveRequestResponse()
		{	
		}
	}
}
