//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/9/2017 2:39:33 PM by user nickkirschke
//
//     Type: CTX
//     Transaction ID: GET.FACULTY.ASGMT.AMTS
//     Application: HR
//     Environment: coldevwapp01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.HumanResources.Transactions
{
	[DataContract]
	public class AssignmentAmounts
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ASSOC.ENTRY.ID", InBoundData = true, OutBoundData = true)]
		public string AssocEntryId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ASGMT.AMOUNT", InBoundData = true, OutBoundData = true)]
		public string AsgmtAmount { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "PAC.LP.ASGMTS.ID", InBoundData = true, OutBoundData = true)]
		public string PacLpAsgmtsId { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.FACULTY.ASGMT.AMTS", GeneratedDateTime = "10/9/2017 2:39:33 PM", User = "nickkirschke")]
	[SctrqDataContract(Application = "HR", DataContractVersion = 1)]
	public class GetFacultyAsgmtAmtsRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "Grp:ASGMT.AMOUNT", InBoundData = true)]
		public List<AssignmentAmounts> AssignmentAmounts { get; set; }

		public GetFacultyAsgmtAmtsRequest()
		{	
			AssignmentAmounts = new List<AssignmentAmounts>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.FACULTY.ASGMT.AMTS", GeneratedDateTime = "10/9/2017 2:39:33 PM", User = "nickkirschke")]
	[SctrqDataContract(Application = "HR", DataContractVersion = 1)]
	public class GetFacultyAsgmtAmtsResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "Grp:ASGMT.AMOUNT", OutBoundData = true)]
		public List<AssignmentAmounts> AssignmentAmounts { get; set; }

		public GetFacultyAsgmtAmtsResponse()
		{	
			AssignmentAmounts = new List<AssignmentAmounts>();
		}
	}
}
