//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 3/16/2018 5:12:42 PM by user asainju1
//
//     Type: CTX
//     Transaction ID: UPDATE.EMPLOYEE
//     Application: HR
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.HumanResources.Transactions
{
	[DataContract]
	public class UpdateEmployeeErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.EMPLOYEE", GeneratedDateTime = "3/16/2018 5:12:42 PM", User = "asainju1")]
	[SctrqDataContract(Application = "HR", DataContractVersion = 1)]
	public class UpdateEmployeeRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.GUID", InBoundData = true)]        
		public string EmployeeGuid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.ID", InBoundData = true)]        
		public string EmployeeId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.PERSON.ID", InBoundData = true)]        
		public string EmployeePersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.LOCATION", InBoundData = true)]        
		public string EmployeeLocation { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.STATUS", InBoundData = true)]        
		public string EmployeeStatus { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.PAY.CLASS", InBoundData = true)]        
		public string EmployeePayClass { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.PAY.STATUS", InBoundData = true)]        
		public string EmployeePayStatus { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.BENEFIT.STATUS", InBoundData = true)]        
		public string EmployeeBenefitStatus { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "EMPLOYEE.PAY.PERIOD.HOURS", InBoundData = true)]        
		public List<Nullable<Decimal>> EmployeePayPeriodHours { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "EMPLOYEE.START.DATE", InBoundData = true)]        
		public Nullable<DateTime> EmployeeStartDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "EMPLOYEE.END.DATE", InBoundData = true)]        
		public Nullable<DateTime> EmployeeEndDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.STATUS.END.REASON", InBoundData = true)]        
		public string EmployeeStatusEndReason { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.REHIRE.CODE", InBoundData = true)]        
		public string EmployeeRehireCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		public UpdateEmployeeRequest()
		{	
			EmployeePayPeriodHours = new List<Nullable<Decimal>>();
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.EMPLOYEE", GeneratedDateTime = "3/16/2018 5:12:42 PM", User = "asainju1")]
	[SctrqDataContract(Application = "HR", DataContractVersion = 1)]
	public class UpdateEmployeeResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.GUID", OutBoundData = true)]        
		public string EmployeeGuid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EMPLOYEE.ID", OutBoundData = true)]        
		public string EmployeeId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<UpdateEmployeeErrors> UpdateEmployeeErrors { get; set; }

		public UpdateEmployeeResponse()
		{	
			UpdateEmployeeErrors = new List<UpdateEmployeeErrors>();
		}
	}
}
