//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 3:08:16 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: COURSE.SEC.FACULTY
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "CourseSecFaculty")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 3:08:16 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "COURSE.SEC.FACULTY", EntityType = "PHYS")]
	public class CourseSecFaculty : IColleagueGuidEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
	
		/// <summary>
		/// Record GUID
		/// </summary>
		[DataMember(Name = "RecordGuid")]
		public string RecordGuid { get; set; }

		/// <summary>
		/// Record Model Name
		/// </summary>
		[DataMember(Name = "RecordModelName")]
		public string RecordModelName { get; set; }	
		
		/// <summary>
		/// CDD Name: CSF.COURSE.SECTION
		/// </summary>
		[DataMember(Order = 0, Name = "CSF.COURSE.SECTION")]
		public string CsfCourseSection { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.FACULTY
		/// </summary>
		[DataMember(Order = 1, Name = "CSF.FACULTY")]
		public string CsfFaculty { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.INSTR.METHOD
		/// </summary>
		[DataMember(Order = 2, Name = "CSF.INSTR.METHOD")]
		public string CsfInstrMethod { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.FACULTY.LOAD
		/// </summary>
		[DataMember(Order = 3, Name = "CSF.FACULTY.LOAD")]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public Decimal? CsfFacultyLoad { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.TEACHING.ARRANGEMENT
		/// </summary>
		[DataMember(Order = 4, Name = "CSF.TEACHING.ARRANGEMENT")]
		public string CsfTeachingArrangement { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.FACULTY.PCT
		/// </summary>
		[DataMember(Order = 5, Name = "CSF.FACULTY.PCT")]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public Decimal? CsfFacultyPct { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.START.DATE
		/// </summary>
		[DataMember(Order = 6, Name = "CSF.START.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? CsfStartDate { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.END.DATE
		/// </summary>
		[DataMember(Order = 7, Name = "CSF.END.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? CsfEndDate { get; set; }
		
		/// <summary>
		/// CDD Name: CSF.PAC.LP.ASGMT
		/// </summary>
		[DataMember(Order = 23, Name = "CSF.PAC.LP.ASGMT")]
		public string CsfPacLpAsgmt { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}