//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 8/1/2019 2:07:29 PM by user pbhaumik2
//
//     Type: ENTITY
//     Entity: DA.DEFAULTS
//     Application: ST
//     Environment: devcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "DaDefaults")]
	[ColleagueDataContract(GeneratedDateTime = "8/1/2019 2:07:29 PM", User = "pbhaumik2")]
	[EntityDataContract(EntityName = "DA.DEFAULTS", EntityType = "PERM")]
	public class DaDefaults : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: DA.RELATED.COURSES
		/// </summary>
		[DataMember(Order = 3, Name = "DA.RELATED.COURSES")]
		public string DaRelatedCourses { get; set; }
		
		/// <summary>
		/// CDD Name: DA.EXTRA.CODE
		/// </summary>
		[DataMember(Order = 11, Name = "DA.EXTRA.CODE")]
		public string DaExtraCode { get; set; }
		
		/// <summary>
		/// CDD Name: DA.INCLUDE.FAILURES
		/// </summary>
		[DataMember(Order = 12, Name = "DA.INCLUDE.FAILURES")]
		public string DaIncludeFailures { get; set; }
		
		/// <summary>
		/// CDD Name: DA.DEFAULT.SORT.OVERRIDE
		/// </summary>
		[DataMember(Order = 24, Name = "DA.DEFAULT.SORT.OVERRIDE")]
		public string DaDefaultSortOverride { get; set; }
		
		/// <summary>
		/// CDD Name: DA.HIDE.ANT.CMPL.DT.IN.SS.MP
		/// </summary>
		[DataMember(Order = 26, Name = "DA.HIDE.ANT.CMPL.DT.IN.SS.MP")]
		public string DaHideAntCmplDtInSsMp { get; set; }
		
		/// <summary>
		/// CDD Name: DA.RELATED.COURSES.FLAG
		/// </summary>
		[DataMember(Order = 27, Name = "DA.RELATED.COURSES.FLAG")]
		public string DaRelatedCoursesFlag { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}