//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 7/12/2019 11:10:28 AM by user jmansfield
//
//     Type: ENTITY
//     Entity: GRADE.SUBSCHEMES
//     Application: ST
//     Environment: dvcoll_wstst01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "GradeSubschemes")]
	[ColleagueDataContract(GeneratedDateTime = "7/12/2019 11:10:28 AM", User = "jmansfield")]
	[EntityDataContract(EntityName = "GRADE.SUBSCHEMES", EntityType = "PHYS")]
	public class GradeSubschemes : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: GSS.GRADE.SCHEMES.ID
		/// </summary>
		[DataMember(Order = 0, Name = "GSS.GRADE.SCHEMES.ID")]
		public string GssGradeSchemesId { get; set; }
		
		/// <summary>
		/// CDD Name: GSS.DESCRIPTION
		/// </summary>
		[DataMember(Order = 1, Name = "GSS.DESCRIPTION")]
		public string GssDescription { get; set; }
		
		/// <summary>
		/// CDD Name: GSS.GRADES
		/// </summary>
		[DataMember(Order = 6, Name = "GSS.GRADES")]
		public List<string> GssGrades { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}