//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 5/23/2018 10:50:03 AM by user dvcoll-srm
//
//     Type: ENTITY
//     Entity: INTG.CRS.TITLE.TYPES
//     Application: ST
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "IntgCrsTitleTypes")]
	[ColleagueDataContract(GeneratedDateTime = "5/23/2018 10:50:03 AM", User = "dvcoll-srm")]
	[EntityDataContract(EntityName = "INTG.CRS.TITLE.TYPES", EntityType = "PHYS")]
	public class IntgCrsTitleTypes : IColleagueGuidEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
	
		/// <summary>
		/// Record GUID
		/// </summary>
		[DataMember(Name = "RecordGuid")]
		public string RecordGuid { get; set; }

		/// <summary>
		/// Record Model Name
		/// </summary>
		[DataMember(Name = "RecordModelName")]
		public string RecordModelName { get; set; }	
		
		/// <summary>
		/// CDD Name: ICTT.TITLE
		/// </summary>
		[DataMember(Order = 0, Name = "ICTT.TITLE")]
		public string IcttTitle { get; set; }
		
		/// <summary>
		/// CDD Name: ICTT.DESC
		/// </summary>
		[DataMember(Order = 1, Name = "ICTT.DESC")]
		public string IcttDesc { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}