//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 3:13:37 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: ORG.TYPES
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "OrgTypes")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 3:13:37 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "ORG.TYPES", EntityType = "PHYS")]
	public class OrgTypes : IColleagueGuidEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
	
		/// <summary>
		/// Record GUID
		/// </summary>
		[DataMember(Name = "RecordGuid")]
		public string RecordGuid { get; set; }

		/// <summary>
		/// Record Model Name
		/// </summary>
		[DataMember(Name = "RecordModelName")]
		public string RecordModelName { get; set; }	
		
		/// <summary>
		/// CDD Name: ORGT.DESC
		/// </summary>
		[DataMember(Order = 0, Name = "ORGT.DESC")]
		public string OrgtDesc { get; set; }
		
		/// <summary>
		/// CDD Name: ORGT.PILOT.FLAG
		/// </summary>
		[DataMember(Order = 19, Name = "ORGT.PILOT.FLAG")]
		public string OrgtPilotFlag { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}