//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 6/17/2022 12:22:59 PM by user ritikakumari
//
//     Type: ENTITY
//     Entity: STU.REL.DENY.ACCESS
//     Application: ST
//     Environment: dvcoll_wstst01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "StuRelDenyAccess")]
	[ColleagueDataContract(GeneratedDateTime = "6/17/2022 12:22:59 PM", User = "ritikakumari")]
	[EntityDataContract(EntityName = "STU.REL.DENY.ACCESS", EntityType = "PHYS")]
	public class StuRelDenyAccess : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: STU.REL.DENY.ACCESS.ALL
		/// </summary>
		[DataMember(Order = 6, Name = "STU.REL.DENY.ACCESS.ALL")]
		public string StuRelDenyAccessAll { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}