//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 3:20:22 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: TAX.FORM.1098.FORMS
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Student.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "TaxForm1098Forms")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 3:20:22 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "TAX.FORM.1098.FORMS", EntityType = "PHYS")]
	public class TaxForm1098Forms : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: TF98F.TAX.FORM
		/// </summary>
		[DataMember(Order = 0, Name = "TF98F.TAX.FORM")]
		public string Tf98fTaxForm { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.TAX.YEAR
		/// </summary>
		[DataMember(Order = 1, Name = "TF98F.TAX.YEAR")]
		public int? Tf98fTaxYear { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.STUDENT
		/// </summary>
		[DataMember(Order = 2, Name = "TF98F.STUDENT")]
		public string Tf98fStudent { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.INSTITUTION
		/// </summary>
		[DataMember(Order = 3, Name = "TF98F.INSTITUTION")]
		public string Tf98fInstitution { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.CORRECTION.IND
		/// </summary>
		[DataMember(Order = 5, Name = "TF98F.CORRECTION.IND")]
		public string Tf98fCorrectionInd { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.NAME
		/// </summary>
		[DataMember(Order = 8, Name = "TF98F.NAME")]
		public string Tf98fName { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.NAME2
		/// </summary>
		[DataMember(Order = 9, Name = "TF98F.NAME2")]
		public string Tf98fName2 { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.ADDRESS
		/// </summary>
		[DataMember(Order = 10, Name = "TF98F.ADDRESS")]
		public string Tf98fAddress { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.CITY
		/// </summary>
		[DataMember(Order = 11, Name = "TF98F.CITY")]
		public string Tf98fCity { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.STATE
		/// </summary>
		[DataMember(Order = 12, Name = "TF98F.STATE")]
		public string Tf98fState { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.ZIP
		/// </summary>
		[DataMember(Order = 13, Name = "TF98F.ZIP")]
		public string Tf98fZip { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.COUNTRY
		/// </summary>
		[DataMember(Order = 14, Name = "TF98F.COUNTRY")]
		public string Tf98fCountry { get; set; }
		
		/// <summary>
		/// CDD Name: TF98F.TAX.FORM.1098.BOXES
		/// </summary>
		[DataMember(Order = 18, Name = "TF98F.TAX.FORM.1098.BOXES")]
		public List<string> Tf98fTaxForm1098Boxes { get; set; }
		
		/// <summary>
		/// CDD Name: TAX.FORM.1098.FORMS.ADDDATE
		/// </summary>
		[DataMember(Order = 23, Name = "TAX.FORM.1098.FORMS.ADDDATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? TaxForm1098FormsAdddate { get; set; }
		
		/// <summary>
		/// CDD Name: TAX.FORM.1098.FORMS.ADDTIME
		/// </summary>
		[DataMember(Order = 25, Name = "TAX.FORM.1098.FORMS.ADDTIME")]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? TaxForm1098FormsAddtime { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}