//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.1
//     Last generated on 12/3/2019 9:51:32 AM by user tshadley
//
//     Type: CTX
//     Transaction ID: XCTX.F09.REPORT
//     Application: ST
//     Environment: F09
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.F09.Transactions
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.1")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "XCTX.F09.REPORT", GeneratedDateTime = "12/3/2019 9:51:32 AM", User = "tshadley")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class ctxF09ReportRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ID", InBoundData = true)]        
		public string Id { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.REPORT", InBoundData = true)]        
		public string Report { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.REQUEST.TYPE", InBoundData = true)]        
		public string RequestType { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.JSON.REQUEST", InBoundData = true)]        
		public string JsonRequest { get; set; }

		public ctxF09ReportRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.1")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "XCTX.F09.REPORT", GeneratedDateTime = "12/3/2019 9:51:32 AM", User = "tshadley")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class ctxF09ReportResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.RESPOND.TYPE", OutBoundData = true)]        
		public string RespondType { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MSG", OutBoundData = true)]        
		public string Msg { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.JSON.REPORT.OPTIONS", OutBoundData = true)]        
		public string JsonReportOptions { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.HTML.REPORT", OutBoundData = true)]        
		public string HtmlReport { get; set; }

		public ctxF09ReportResponse()
		{	
		}
	}
}
