//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 4/10/2019 12:23:26 PM by user tshadley
//
//     Type: CTX
//     Transaction ID: XCTX.F09.ADMIN.TRACKING.SHEET
//     Application: ST
//     Environment: F09 ProjDB
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.F09.Transactions
{
	[DataContract]
	public class StuTracking
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "AL.STU.ID", OutBoundData = true)]
		public string StuId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.STU.NAME", OutBoundData = true)]
		public string StuName { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.STAD.TYPE", OutBoundData = true)]
		public string StadType { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.PROG", OutBoundData = true)]
		public string Prog { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.REVIEW.TERMS", OutBoundData = true)]
		public string ReviewTerms { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "XCTX.F09.ADMIN.TRACKING.SHEET", GeneratedDateTime = "4/10/2019 12:23:26 PM", User = "tshadley")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class ctxF09AdminTrackingSheetRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.ID", InBoundData = true)]        
		public string Id { get; set; }

		public ctxF09AdminTrackingSheetRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "XCTX.F09.ADMIN.TRACKING.SHEET", GeneratedDateTime = "4/10/2019 12:23:26 PM", User = "tshadley")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class ctxF09AdminTrackingSheetResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:AL.STU.ID", OutBoundData = true)]
		public List<StuTracking> StuTracking { get; set; }

		public ctxF09AdminTrackingSheetResponse()
		{	
			StuTracking = new List<StuTracking>();
		}
	}
}
