//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 1:38:57 PM by user dvcoll-schandraseka
//
//     Type: CTX
//     Transaction ID: GET.PROPOSED.PAYMENT.PLAN.INFO
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Finance.Transactions
{
	[DataContract]
	public class ProposedScheduledPayments
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.SCHED.PMT.IDS", OutBoundData = true)]
		public string OutSchedPmtIds { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.SCHED.PMT.AMTS", OutBoundData = true)]
		public Nullable<Decimal> OutSchedPmtAmts { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "OUT.SCHED.PMT.DUE.DATES", OutBoundData = true)]
		public Nullable<DateTime> OutSchedPmtDueDates { get; set; }
	}

	[DataContract]
	public class ProposedPaymentPlanCharges
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.ITEM.INV.ITEM.IDS", OutBoundData = true)]
		public string OutPlanItemInvItemIds { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.ITEM.AMTS", OutBoundData = true)]
		public Nullable<Decimal> OutPlanItemAmounts { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.ITEM.SETUP.CHG.FLAGS", OutBoundData = true)]
		public string OutPlanItemSetupChgFlags { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.ITEM.AUTO.MOD.FLAGS", OutBoundData = true)]
		public string OutPlanItemAutoModFlags { get; set; }
	}

	[DataContract]
	public class ProposedInvoiceItems
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.AR.INVOICE.ITEM.IDS", OutBoundData = true)]
		public string OutArInvoiceItemIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.AR.INVOICE.ITEM.INVOICE.IDS", OutBoundData = true)]
		public string OutArInvoiceItemInvoiceIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.AR.INVOICE.ITEM.DESCS", OutBoundData = true)]
		public string OutArInvoiceItemDescs { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.AR.INVOICE.ITEM.AR.CODES", OutBoundData = true)]
		public string OutArInvoiceItemArCodes { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.AR.INVOICE.ITEM.CHARGE.AMTS", OutBoundData = true)]
		public Nullable<Decimal> OutArInvoiceItemChargeAmts { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.AR.INVOICE.ITEM.CREDIT.AMTS", OutBoundData = true)]
		public Nullable<Decimal> OutArInvoiceItemCreditAmts { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.PROPOSED.PAYMENT.PLAN.INFO", GeneratedDateTime = "10/4/2017 1:38:57 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class GetProposedPaymentPlanInfoRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "IN.PERSON.ID", InBoundData = true)]        
		public string InPersonId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "IN.AR.TYPE", InBoundData = true)]        
		public string InArType { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "IN.PAY.PLAN.TEMPLATE.ID", InBoundData = true)]        
		public string InPayPlanTemplateId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "IN.TERM.ID", InBoundData = true)]        
		public string InTermId { get; set; }

		[DataMember(IsRequired = true)]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "IN.FIRST.PMT.DATE", InBoundData = true)]        
		public Nullable<DateTime> InFirstPmtDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "IN.PLAN.AMT", InBoundData = true)]        
		public Nullable<Decimal> InPlanAmt { get; set; }

		public GetProposedPaymentPlanInfoRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.PROPOSED.PAYMENT.PLAN.INFO", GeneratedDateTime = "10/4/2017 1:38:57 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class GetProposedPaymentPlanInfoResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.ID", OutBoundData = true)]        
		public string OutPlanId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.AMOUNT", OutBoundData = true)]        
		public Nullable<Decimal> OutPlanAmount { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.FREQUENCY", OutBoundData = true)]        
		public string OutPlanFrequency { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.PMTS.COUNT", OutBoundData = true)]        
		public Nullable<int> OutPlanPmtsCount { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.SETUP.CHG.AMT", OutBoundData = true)]        
		public Nullable<Decimal> OutPlanSetupChgAmt { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.SETUP.CHG.PCT", OutBoundData = true)]        
		public Nullable<Decimal> OutPlanSetupChgPct { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.DOWN.PAY.PCT", OutBoundData = true)]        
		public Nullable<Decimal> OutPlanDownPayPct { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.PLAN.GRACE.DAYS", OutBoundData = true)]        
		public Nullable<int> OutPlanGraceDays { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.LATE.CHG.AMT", OutBoundData = true)]        
		public Nullable<Decimal> OutPlanLateChgAmt { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "OUT.PLAN.LATE.CHG.PCT", OutBoundData = true)]        
		public Nullable<Decimal> OutPlanLateChgPct { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.ERROR.OCCURRED", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, OutBoundData = true)]        
		public bool OutErrorOccurred { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OUT.ERROR.MESSAGES", OutBoundData = true)]        
		public List<string> OutErrorMessages { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:OUT.SCHED.PMT.IDS", OutBoundData = true)]
		public List<ProposedScheduledPayments> ProposedScheduledPayments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:OUT.PLAN.ITEM.INV.ITEM.IDS", OutBoundData = true)]
		public List<ProposedPaymentPlanCharges> ProposedPaymentPlanCharges { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:OUT.AR.INVOICE.ITEM.IDS", OutBoundData = true)]
		public List<ProposedInvoiceItems> ProposedInvoiceItems { get; set; }

		public GetProposedPaymentPlanInfoResponse()
		{	
			OutErrorMessages = new List<string>();
			ProposedScheduledPayments = new List<ProposedScheduledPayments>();
			ProposedPaymentPlanCharges = new List<ProposedPaymentPlanCharges>();
			ProposedInvoiceItems = new List<ProposedInvoiceItems>();
		}
	}
}
