//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 1:43:38 PM by user dvcoll-schandraseka
//
//     Type: CTX
//     Transaction ID: SFX002AD
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Finance.Transactions
{
	[DataContract]
	public class FinancialActivityChargeGroups
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.GROUP.NAME", OutBoundData = true)]
		public string ChrgGroupName { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.GROUP.TYPE", OutBoundData = true)]
		public string ChrgGroupType { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.DISPLAY.ORDER", OutBoundData = true)]
		public string ChrgDisplayOrder { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.1", OutBoundData = true)]
		public string Section { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.2", OutBoundData = true)]
		public string CourseTitle { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.3", OutBoundData = true)]
		public string Term { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.4", OutBoundData = true)]
		public Nullable<Decimal> Amount { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.5", OutBoundData = true)]
		public Nullable<Decimal> Credits { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN15", OutBoundData = true)]
		public Nullable<Decimal> BillingCredits { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN16", OutBoundData = true)]
		public Nullable<Decimal> Ceus { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.6", OutBoundData = true)]
		public string Days { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.7", OutBoundData = true)]
		public string Times { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.8", OutBoundData = true)]
		public string Classroom { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN.9", OutBoundData = true)]
		public string Instructor { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN10", OutBoundData = true)]
		public string Status { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN11", OutBoundData = true)]
		public string Description { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN12", OutBoundData = true)]
		public Nullable<DateTime> Date { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN13", OutBoundData = true)]
		public string BuildingRoom { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.CHRG.COLUMN14", OutBoundData = true)]
		public string InvoiceNumber { get; set; }
	}

	[DataContract]
	public class FinancialActivityStudentPayments
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.RCPT.NO", OutBoundData = true)]
		public string StuPayRcptNo { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.RCPT.DATE", OutBoundData = true)]
		public Nullable<DateTime> StuPayRcptDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.TERM", OutBoundData = true)]
		public string StuPayTerm { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.DESCRIPTION", OutBoundData = true)]
		public string StuPayDescription { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.AMOUNT", OutBoundData = true)]
		public Nullable<Decimal> StuPayAmount { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.METHOD", OutBoundData = true)]
		public string StuPayMethod { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.RCPT.ID", OutBoundData = true)]
		public string StuPayRcptId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.STU.PAY.REF.NO", OutBoundData = true)]
		public string StuPayRefNo { get; set; }
	}

	[DataContract]
	public class FinancialActivitySponsorPayments
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.SPON.PAY.ID", OutBoundData = true)]
		public string SponPayId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.SPON.PAY.DATE", OutBoundData = true)]
		public Nullable<DateTime> SponPayDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.SPON.PAY.TERM", OutBoundData = true)]
		public string SponPayTerm { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.SPON.PAY.SPONSOR", OutBoundData = true)]
		public string SponPaySponsor { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.SPON.PAY.AMOUNT", OutBoundData = true)]
		public Nullable<Decimal> SponPayAmount { get; set; }
	}

	[DataContract]
	public class FinancialActivityFAPayments
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.FA.TRANS.ID", OutBoundData = true)]
		public string FaTransId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.FA.TRANS.DATE", OutBoundData = true)]
		public Nullable<DateTime> FaTransDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.FA.TRANS.TERM", OutBoundData = true)]
		public string FaTransTerm { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.FA.TRANS.DESC", OutBoundData = true)]
		public string FaTransDesc { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.FA.TRANS.AMOUNT", OutBoundData = true)]
		public Nullable<Decimal> FaTransAmount { get; set; }
	}

	[DataContract]
	public class FinancialActivityAppliedDeposits
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEP.RCPT.NO", OutBoundData = true)]
		public string DepRcptNo { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.DEP.DATE", OutBoundData = true)]
		public Nullable<DateTime> DepDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEP.TERM", OutBoundData = true)]
		public string DepTerm { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEP.TYPE.DESC", OutBoundData = true)]
		public string DepTypeDesc { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.DEP.AMOUNT", OutBoundData = true)]
		public Nullable<Decimal> DepAmount { get; set; }
	}

	[DataContract]
	public class FinancialActivityRefunds
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.VOUCHER.ID", OutBoundData = true)]
		public string RefundVoucherId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.REFUND.DATE", OutBoundData = true)]
		public Nullable<DateTime> RefundDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.TERM", OutBoundData = true)]
		public string RefundTerms { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.DESCRIPTION", OutBoundData = true)]
		public string RefundDescription { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.REFUND.AMOUNT", OutBoundData = true)]
		public Nullable<Decimal> RefundAmount { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.PAY.METHOD", OutBoundData = true)]
		public string RefundPayMethod { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.STATUS", OutBoundData = true)]
		public string RefundStatus { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.REFUND.STATUS.DATE", OutBoundData = true)]
		public Nullable<DateTime> RefundStatusDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.TRANS.NO", OutBoundData = true)]
		public string RefundTransNo { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.CC.LAST4", OutBoundData = true)]
		public string RefundCcLast4 { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.REFUND.CHECK.NO", OutBoundData = true)]
		public string RefundCheckNo { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.REFUND.CHECK.DATE", OutBoundData = true)]
		public Nullable<DateTime> RefundCheckDate { get; set; }
	}

	[DataContract]
	public class FinancialActivityDeposits
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.IDS", OutBoundData = true)]
		public string DepositIds { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.DATES", OutBoundData = true)]
		public Nullable<DateTime> DepositDates { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.TERMS", OutBoundData = true)]
		public string DepositTerms { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.TYPE.DESCS", OutBoundData = true)]
		public string DepositTypeDescs { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.AMTS", OutBoundData = true)]
		public Nullable<Decimal> DepositAmts { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.APPLIED.AMTS", OutBoundData = true)]
		public Nullable<Decimal> DepositAppliedAmts { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.REFUND.AMTS", OutBoundData = true)]
		public Nullable<Decimal> DepositRefundAmts { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.OTHER.AMTS", OutBoundData = true)]
		public Nullable<Decimal> DepositOtherAmts { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.BALANCE", OutBoundData = true)]
		public Nullable<Decimal> DepositBalance { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "XL.DEPOSIT.RCPT.ID", OutBoundData = true)]
		public string DepositRcptId { get; set; }
	}

	[DataContract]
	public class AllChargeGroups
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ALL.CHARGE.GROUP.NAMES", OutBoundData = true)]
		public string AllChargeGroupNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ALL.CHARGE.GROUP.TYPES", OutBoundData = true)]
		public string AllChargeGroupTypes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ALL.CHARGE.GROUP.ORDERS", OutBoundData = true)]
		public Nullable<int> AllChargeGroupOrders { get; set; }
	}

	[DataContract]
	public class InboundTerms
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "AL.TERMS.ID", InBoundData = true)]
		public string TermsId { get; set; }
	}

	[DataContract]
	public class PaymentPlans
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "PLAN.ID", OutBoundData = true)]
		public string PlanId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "PLAN.TYPE", OutBoundData = true)]
		public string PlanType { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "PLAN.TERM", OutBoundData = true)]
		public string PlanTerm { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "PLAN.ORIG.AMOUNT", OutBoundData = true)]
		public Nullable<Decimal> PlanOrigAmount { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "PLAN.BALANCE", OutBoundData = true)]
		public Nullable<Decimal> PlanBalance { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "PLAN.AMT.DUE", OutBoundData = true)]
		public Nullable<Decimal> PlanAmtDue { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "PLAN.APPROVAL.ID", OutBoundData = true)]
		public string PlanApprovalId { get; set; }
	}

	[DataContract]
	public class PlanSchedules
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "SCHEDULE.PLAN.ID", OutBoundData = true)]
		public string SchedulePlanId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.DUE.DATE", OutBoundData = true)]
		public Nullable<DateTime> ScheduleDueDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.AMT.DUE", OutBoundData = true)]
		public Nullable<Decimal> ScheduleAmtDue { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.SETUP.CHARGE", OutBoundData = true)]
		public Nullable<Decimal> ScheduleSetupCharge { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.LATE.CHARGE", OutBoundData = true)]
		public Nullable<Decimal> ScheduleLateCharge { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.AMT.PAID", OutBoundData = true)]
		public Nullable<Decimal> ScheduleAmtPaid { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.NET.AMT.DUE", OutBoundData = true)]
		public Nullable<Decimal> ScheduleNetAmtDue { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "SCHEDULE.DATE.PAID", OutBoundData = true)]
		public Nullable<DateTime> ScheduleDatePaid { get; set; }
	}

	[DataContract]
	public class AnticipatedFinancialAid
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "FA.AWARD.PERIOD.AWARD", OutBoundData = true)]
		public string FaAwardPeriodAward { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FA.AWARD.DESC", OutBoundData = true)]
		public string FaAwardDesc { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FA.AWARD.AMT", OutBoundData = true)]
		public Nullable<Decimal> FaAwardAmt { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FA.AWARD.OTHER.AMT", OutBoundData = true)]
		public Nullable<Decimal> FaAwardOtherAmt { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FA.AWARD.LOAN.FEE", OutBoundData = true)]
		public Nullable<Decimal> FaAwardLoanFee { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FA.AWARD.INELIG.AMT", OutBoundData = true)]
		public Nullable<Decimal> FaAwardIneligAmt { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FA.AWARD.COMMENTS", OutBoundData = true)]
		public string FaAwardComments { get; set; }
	}

	[DataContract]
	public class AnticipatedAidTerms
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "FA.TERMS.PERIOD.AWARD", OutBoundData = true)]
		public string FaTermsPeriodAward { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FA.TERMS.AWARD.TERM", OutBoundData = true)]
		public string FaTermsAwardTerm { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FA.TERMS.DISB.AMT", OutBoundData = true)]
		public Nullable<Decimal> FaTermsDisbAmt { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FA.TERMS.ANT.AMT", OutBoundData = true)]
		public Nullable<Decimal> FaTermsAntAmt { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "SFX002AD", GeneratedDateTime = "10/4/2017 1:43:38 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 2)]
	public class StudentFinancialActivityAdminRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "PERSON.ID", InBoundData = true)]        
		public string PersonId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "A.START.DATE", InBoundData = true)]        
		public Nullable<DateTime> StartDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "A.END.DATE", InBoundData = true)]        
		public Nullable<DateTime> EndDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:AL.TERMS.ID", InBoundData = true)]
		public List<InboundTerms> InboundTerms { get; set; }

		public StudentFinancialActivityAdminRequest()
		{	
			InboundTerms = new List<InboundTerms>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "SFX002AD", GeneratedDateTime = "10/4/2017 1:43:38 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 2)]
	public class StudentFinancialActivityAdminResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "PERSON.NAME", OutBoundData = true)]        
		public string PersonName { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.CHRG.GROUP.NAME", OutBoundData = true)]
		public List<FinancialActivityChargeGroups> FinancialActivityChargeGroups { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.STU.PAY.RCPT.NO", OutBoundData = true)]
		public List<FinancialActivityStudentPayments> FinancialActivityStudentPayments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.SPON.PAY.ID", OutBoundData = true)]
		public List<FinancialActivitySponsorPayments> FinancialActivitySponsorPayments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.FA.TRANS.ID", OutBoundData = true)]
		public List<FinancialActivityFAPayments> FinancialActivityFAPayments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.DEP.RCPT.NO", OutBoundData = true)]
		public List<FinancialActivityAppliedDeposits> FinancialActivityAppliedDeposits { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.REFUND.VOUCHER.ID", OutBoundData = true)]
		public List<FinancialActivityRefunds> FinancialActivityRefunds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:XL.DEPOSIT.IDS", OutBoundData = true)]
		public List<FinancialActivityDeposits> FinancialActivityDeposits { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ALL.CHARGE.GROUP.NAMES", OutBoundData = true)]
		public List<AllChargeGroups> AllChargeGroups { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:PLAN.ID", OutBoundData = true)]
		public List<PaymentPlans> PaymentPlans { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:SCHEDULE.PLAN.ID", OutBoundData = true)]
		public List<PlanSchedules> PlanSchedules { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:FA.AWARD.PERIOD.AWARD", OutBoundData = true)]
		public List<AnticipatedFinancialAid> AnticipatedFinancialAid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:FA.TERMS.PERIOD.AWARD", OutBoundData = true)]
		public List<AnticipatedAidTerms> AnticipatedAidTerms { get; set; }

		public StudentFinancialActivityAdminResponse()
		{	
			FinancialActivityChargeGroups = new List<FinancialActivityChargeGroups>();
			FinancialActivityStudentPayments = new List<FinancialActivityStudentPayments>();
			FinancialActivitySponsorPayments = new List<FinancialActivitySponsorPayments>();
			FinancialActivityFAPayments = new List<FinancialActivityFAPayments>();
			FinancialActivityAppliedDeposits = new List<FinancialActivityAppliedDeposits>();
			FinancialActivityRefunds = new List<FinancialActivityRefunds>();
			FinancialActivityDeposits = new List<FinancialActivityDeposits>();
			AllChargeGroups = new List<AllChargeGroups>();
			PaymentPlans = new List<PaymentPlans>();
			PlanSchedules = new List<PlanSchedules>();
			AnticipatedFinancialAid = new List<AnticipatedFinancialAid>();
			AnticipatedAidTerms = new List<AnticipatedAidTerms>();
		}
	}
}
