using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Ellucian.Colleague.Domain.Student.Entities;



namespace Ellucian.Colleague.Domain.Student.Tests
{
    public class TestAwardRepository
    {
        public IEnumerable<Major> GetMajors()
        {
            List<Major> Majors = new List<Major> {
                                            new Major("ACCT",	"Accounting"),
                                            new Major("AGBU",	"Agriculture Business"),
                                            new Major("AGME",	"Agriculture Mechanics"),
                                            new Major("ANSC",	"Animal Science"),
                                            new Major("ANTH",	"Anthropology"),
                                            new Major("AOJU",	"Administration of Justice"),
                                            new Major("ART",	"Art"),
                                            new Major("ARTH",	"Art History"),
                                            new Major("AUTO",	"Automotive Technology"),
                                            new Major("AVIA",	"Aviation"),
                                            new Major("BIOC",	"BioChemistry"),
                                            new Major("BIOL",	"Biology"),
                                            new Major("BUSN",	"Business Administration"),
                                            new Major("CHEM",	"Chemistry"),
                                            new Major("CLAS",	"Classical Studies"),
                                            new Major("CNED",	"Continuing Education"),
                                            new Major("COMM",	"Communications"),
                                            new Major("COMP",	"Computer Science"),
                                            new Major("CRIM",	"Criminology"),
                                            new Major("CROP",	"Crop Science"),
                                            new Major("CULS",	"Culinary Studies"),
                                            new Major("DANC",	"Dance"),
                                            new Major("DENT",	"Dental Hygeine"),
                                            new Major("DRAM",	"Drama"),
                                            new Major("ECED",	"Early Childhood Education"),
                                            new Major("ECON",	"Economics"),
                                            new Major("EDUC",	"Education"),
                                            new Major("ENGL",	"English"),
                                            new Major("ENGR",	"Engineering"),
                                            new Major("FILM",	"Film Studies"),
                                            new Major("FORE",	"Forestry"),
                                            new Major("FREN",	"French"),
                                            new Major("GEOL",	"Geology"),
                                            new Major("GERM",	"German"),
                                            new Major("HEBR",	"Hebrew"),
                                            new Major("HIND",	"Hindu"),
                                            new Major("HIST",	"History"),
                                            new Major("HLTH",	"Health"),
                                            new Major("HUMT",	"Humanities"),
                                            new Major("ITAL",	"Italian"),
                                            new Major("LANG",	"Languages"),
                                            new Major("LAW" ,	"Legal Studies"),
                                            new Major("MATH",	"Mathematics"),
                                            new Major("MDLL",	"Modern Language & Literature"),
                                            new Major("MEDT",	"Medical Lab Technology"),
                                            new Major("MGMT",	"Graduate Business Management"),
                                            new Major("MKTG",	"Marketing"),
                                            new Major("MORT",	"Mortuary Science"),
                                            new Major("MUSC",	"Music"),
                                            new Major("NURS",	"Nursing"),
                                            new Major("PARA",	"Paralegal Technology"),
                                            new Major("PARK",	"Park Ranger Technology"),
                                            new Major("PERF",	"Performing Arts"),
                                            new Major("PHED",	"Physical Education"),
                                            new Major("PHIL",	"Philosophy"),
                                            new Major("PHYS",	"Physics"),
                                            new Major("POLI",	"Political Science"),
                                            new Major("PSYC",	"Psychology"),
                                            new Major("R2OR",	"R25 Testing"),
                                            new Major("REAL",	"Real Estate/Land Appraisal"),
                                            new Major("RELG",	"Religious Studies"),
                                            new Major("SOCI",	"Sociology"),
                                            new Major("SPAN",	"Spanish"),
                                            new Major("SRCH",    "Special Major for SearchTestOne"), 
                                            new Major("STAT",	"Statistics"),
                                            new Major("SZI ",	"Sziede Test Major"),
                                            new Major("TECH",	"Technology"),
                                            new Major("TRUK",	"Truck Driving Technology"),
                                            new Major("WELD",	"Welding"),
                                            new Major("AAAA",   "AAAAaaMajor")
                                  };
            return Majors;
        }

        public IEnumerable<Minor> GetMinors()
        {
            List<Minor> Minors = new List<Minor> {
                                            new Minor("ACCT",	"Accounting"),
                                            new Minor("AGBU",	"Agriculture Business"),
                                            new Minor("AGME",	"Agriculture Mechanics"),
                                            new Minor("ANSC",	"Animal Science"),
                                            new Minor("ANTH",	"Anthropology"),
                                            new Minor("AOJU",	"Administration of Justice"),
                                            new Minor("ART",	"Art"),
                                            new Minor("ARTH",	"Art History"),
                                            new Minor("AUTO",	"Automotive Technology"),
                                            new Minor("AVIA",	"Aviation"),
                                            new Minor("BIOC",	"BioChemistry"),
                                            new Minor("BIOL",	"Biology"),
                                            new Minor("BUSN",	"Business Administration"),
                                            new Minor("CHEM",	"Chemistry"),
                                            new Minor("CLAS",	"Classical Studies"),
                                            new Minor("CNED",	"Continuing Education"),
                                            new Minor("COMM",	"Communications"),
                                            new Minor("COMP",	"Computer Science"),
                                            new Minor("CRIM",	"Criminology"),
                                            new Minor("CROP",	"Crop Science"),
                                            new Minor("CULS",	"Culinary Studies"),
                                            new Minor("DANC",	"Dance"),
                                            new Minor("DENT",	"Dental Hygeine"),
                                            new Minor("DRAM",	"Drama"),
                                            new Minor("ECED",	"Early Childhood Education"),
                                            new Minor("ECON",	"Economics"),
                                            new Minor("EDUC",	"Education"),
                                            new Minor("ENGL",	"English"),
                                            new Minor("ENGR",	"Engineering"),
                                            new Minor("FILM",	"Film Studies"),
                                            new Minor("FORE",	"Forestry"),
                                            new Minor("FREN",	"French"),
                                            new Minor("GEOL",	"Geology"),
                                            new Minor("GERM",	"German"),
                                            new Minor("HEBR",	"Hebrew"),
                                            new Minor("HIND",	"Hindu"),
                                            new Minor("HIST",	"History"),
                                            new Minor("HLTH",	"Health"),
                                            new Minor("HUMT",	"Humanities"),
                                            new Minor("ITAL",	"Italian"),
                                            new Minor("LANG",	"Languages"),
                                            new Minor("LAW" ,	"Legal Studies"),
                                            new Minor("MATH",	"Mathematics"),
                                            new Minor("MDLL",	"Modern Language & Literature"),
                                            new Minor("MEDT",	"Medical Lab Technology"),
                                            new Minor("MGMT",	"Graduate Business Management"),
                                            new Minor("MKTG",	"Marketing"),
                                            new Minor("MORT",	"Mortuary Science"),
                                            new Minor("MUSC",	"Music"),
                                            new Minor("NURS",	"Nursing"),
                                            new Minor("PARA",	"Paralegal Technology"),
                                            new Minor("PARK",	"Park Ranger Technology"),
                                            new Minor("PERF",	"Performing Arts"),
                                            new Minor("PHED",	"Physical Education"),
                                            new Minor("PHIL",	"Philosophy"),
                                            new Minor("PHYS",	"Physics"),
                                            new Minor("POLI",	"Political Science"),
                                            new Minor("PSYC",	"Psychology"),
                                            new Minor("R2OR",	"R25 Testing"),
                                            new Minor("REAL",	"Real Estate/Land Appraisal"),
                                            new Minor("RELG",	"Religious Studies"),
                                            new Minor("SOCI",	"Sociology"),
                                            new Minor("SPAN",	"Spanish"),
                                            new Minor("SRCH",    "Special Minor for SearchTestOne"), 
                                            new Minor("STAT",	"Statistics"),
                                            new Minor("SZI ",	"Sziede Test Minor"),
                                            new Minor("TECH",	"Technology"),
                                            new Minor("TRUK",	"Truck Driving Technology"),
                                            new Minor("WELD",	"Welding"),
                                            new Minor("AAAA",   "AAAAaaMinor")
                                  };
            return Minors;
        }

        public IEnumerable<Specialization> GetSpecializations()
        {
            List<Specialization> Specializations = new List<Specialization> {
                                            new Specialization("ACCT",	"Accounting"),
                                            new Specialization("AGBU",	"Agriculture Business"),
                                            new Specialization("AGME",	"Agriculture Mechanics"),
                                            new Specialization("ANSC",	"Animal Science"),
                                            new Specialization("ANTH",	"Anthropology"),
                                            new Specialization("AOJU",	"Administration of Justice"),
                                            new Specialization("ART",	"Art"),
                                            new Specialization("ARTH",	"Art History"),
                                            new Specialization("AUTO",	"Automotive Technology"),
                                            new Specialization("AVIA",	"Aviation"),
                                            new Specialization("BIOC",	"BioChemistry"),
                                            new Specialization("BIOL",	"Biology"),
                                            new Specialization("BUSN",	"Business Administration"),
                                            new Specialization("CHEM",	"Chemistry"),
                                            new Specialization("CLAS",	"Classical Studies"),
                                            new Specialization("CNED",	"Continuing Education"),
                                            new Specialization("COMM",	"Communications"),
                                            new Specialization("COMP",	"Computer Science"),
                                            new Specialization("CRIM",	"Criminology"),
                                            new Specialization("CROP",	"Crop Science"),
                                            new Specialization("CULS",	"Culinary Studies"),
                                            new Specialization("DANC",	"Dance"),
                                            new Specialization("DENT",	"Dental Hygeine"),
                                            new Specialization("DRAM",	"Drama"),
                                            new Specialization("ECED",	"Early Childhood Education"),
                                            new Specialization("ECON",	"Economics"),
                                            new Specialization("EDUC",	"Education"),
                                            new Specialization("ENGL",	"English"),
                                            new Specialization("ENGR",	"Engineering"),
                                            new Specialization("FILM",	"Film Studies"),
                                            new Specialization("FORE",	"Forestry"),
                                            new Specialization("FREN",	"French"),
                                            new Specialization("GEOL",	"Geology"),
                                            new Specialization("GERM",	"German"),
                                            new Specialization("HEBR",	"Hebrew"),
                                            new Specialization("HIND",	"Hindu"),
                                            new Specialization("HIST",	"History"),
                                            new Specialization("HLTH",	"Health"),
                                            new Specialization("HUMT",	"Humanities"),
                                            new Specialization("ITAL",	"Italian"),
                                            new Specialization("LANG",	"Languages"),
                                            new Specialization("LAW" ,	"Legal Studies"),
                                            new Specialization("MATH",	"Mathematics"),
                                            new Specialization("MDLL",	"Modern Language & Literature"),
                                            new Specialization("MEDT",	"Medical Lab Technology"),
                                            new Specialization("MGMT",	"Graduate Business Management"),
                                            new Specialization("MKTG",	"Marketing"),
                                            new Specialization("MORT",	"Mortuary Science"),
                                            new Specialization("MUSC",	"Music"),
                                            new Specialization("NURS",	"Nursing"),
                                            new Specialization("PARA",	"Paralegal Technology"),
                                            new Specialization("PARK",	"Park Ranger Technology"),
                                            new Specialization("PERF",	"Performing Arts"),
                                            new Specialization("PHED",	"Physical Education"),
                                            new Specialization("PHIL",	"Philosophy"),
                                            new Specialization("PHYS",	"Physics"),
                                            new Specialization("POLI",	"Political Science"),
                                            new Specialization("PSYC",	"Psychology"),
                                            new Specialization("R2OR",	"R25 Testing"),
                                            new Specialization("REAL",	"Real Estate/Land Appraisal"),
                                            new Specialization("RELG",	"Religious Studies"),
                                            new Specialization("SOCI",	"Sociology"),
                                            new Specialization("SPAN",	"Spanish"),
                                            new Specialization("SRCH",    "Special Specialization for SearchTestOne"), 
                                            new Specialization("STAT",	"Statistics"),
                                            new Specialization("SZI ",	"Sziede Test Specialization"),
                                            new Specialization("TECH",	"Technology"),
                                            new Specialization("TRUK",	"Truck Driving Technology"),
                                            new Specialization("WELD",	"Welding"),
                                            new Specialization("AAAA",   "AAAAaaSpecialization")
                                  };
            return Specializations;
        }

        public IEnumerable<Ccd> GetCcds()
        {
            List<Ccd> Ccds = new List<Ccd> {
                                            new Ccd("ACCT",	"Accounting"),
                                            new Ccd("AGBU",	"Agriculture Business"),
                                            new Ccd("AGME",	"Agriculture Mechanics"),
                                            new Ccd("ANSC",	"Animal Science"),
                                            new Ccd("ANTH",	"Anthropology"),
                                            new Ccd("AOJU",	"Administration of Justice"),
                                            new Ccd("ART",	"Art"),
                                            new Ccd("ARTH",	"Art History"),
                                            new Ccd("AUTO",	"Automotive Technology"),
                                            new Ccd("AVIA",	"Aviation"),
                                            new Ccd("BIOC",	"BioChemistry"),
                                            new Ccd("BIOL",	"Biology"),
                                            new Ccd("BUSN",	"Business Administration"),
                                            new Ccd("CHEM",	"Chemistry"),
                                            new Ccd("CLAS",	"Classical Studies"),
                                            new Ccd("CNED",	"Continuing Education"),
                                            new Ccd("COMM",	"Communications"),
                                            new Ccd("COMP",	"Computer Science"),
                                            new Ccd("CRIM",	"Criminology"),
                                            new Ccd("CROP",	"Crop Science"),
                                            new Ccd("CULS",	"Culinary Studies"),
                                            new Ccd("DANC",	"Dance"),
                                            new Ccd("DENT",	"Dental Hygeine"),
                                            new Ccd("DRAM",	"Drama"),
                                            new Ccd("ECED",	"Early Childhood Education"),
                                            new Ccd("ECON",	"Economics"),
                                            new Ccd("EDUC",	"Education"),
                                            new Ccd("ENGL",	"English"),
                                            new Ccd("ENGR",	"Engineering"),
                                            new Ccd("FILM",	"Film Studies"),
                                            new Ccd("FORE",	"Forestry"),
                                            new Ccd("FREN",	"French"),
                                            new Ccd("GEOL",	"Geology"),
                                            new Ccd("GERM",	"German"),
                                            new Ccd("HEBR",	"Hebrew"),
                                            new Ccd("HIND",	"Hindu"),
                                            new Ccd("HIST",	"History"),
                                            new Ccd("HLTH",	"Health"),
                                            new Ccd("HUMT",	"Humanities"),
                                            new Ccd("ITAL",	"Italian"),
                                            new Ccd("LANG",	"Languages"),
                                            new Ccd("LAW" ,	"Legal Studies"),
                                            new Ccd("MATH",	"Mathematics"),
                                            new Ccd("MDLL",	"Modern Language & Literature"),
                                            new Ccd("MEDT",	"Medical Lab Technology"),
                                            new Ccd("MGMT",	"Graduate Business Management"),
                                            new Ccd("MKTG",	"Marketing"),
                                            new Ccd("MORT",	"Mortuary Science"),
                                            new Ccd("MUSC",	"Music"),
                                            new Ccd("NURS",	"Nursing"),
                                            new Ccd("PARA",	"Paralegal Technology"),
                                            new Ccd("PARK",	"Park Ranger Technology"),
                                            new Ccd("PERF",	"Performing Arts"),
                                            new Ccd("PHED",	"Physical Education"),
                                            new Ccd("PHIL",	"Philosophy"),
                                            new Ccd("PHYS",	"Physics"),
                                            new Ccd("POLI",	"Political Science"),
                                            new Ccd("PSYC",	"Psychology"),
                                            new Ccd("R2OR",	"R25 Testing"),
                                            new Ccd("REAL",	"Real Estate/Land Appraisal"),
                                            new Ccd("RELG",	"Religious Studies"),
                                            new Ccd("SOCI",	"Sociology"),
                                            new Ccd("SPAN",	"Spanish"),
                                            new Ccd("SRCH",    "Special Ccd for SearchTestOne"), 
                                            new Ccd("STAT",	"Statistics"),
                                            new Ccd("SZI ",	"Sziede Test Ccd"),
                                            new Ccd("TECH",	"Technology"),
                                            new Ccd("TRUK",	"Truck Driving Technology"),
                                            new Ccd("WELD",	"Welding"),
                                            new Ccd("AAAA",   "AAAAaaCcd")
                                  };
            return Ccds;
        }
    }
}