//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 2/17/2020 8:45:21 PM by user anamika_a 
//
//     Type: CTX
//     Transaction ID: TX.UPDATE.WEB.PO
//     Application: CF
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.ColleagueFinance.Transactions
{
	[DataContract]
	public class AlUpdatedPoLineItems
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.IDS", InBoundData = true)]
		public string AlLineItemIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.DESCS", InBoundData = true)]
		public string AlLineItemDescs { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.QTYS", InBoundData = true)]
		public string AlLineItemQtys { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.PRICES", InBoundData = true)]
		public string AlItemPrices { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.GL.ACCTS", InBoundData = true)]
		public string AlItemGlAccts { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.PROJECT.NOS", InBoundData = true)]
		public string AlItemProjectNos { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.GL.ACCT.AMTS", InBoundData = true)]
		public string AlItemGlAcctAmts { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.UNIT.ISSUES", InBoundData = true)]
		public string AlItemUnitIssues { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.VENDOR.PARTS", InBoundData = true)]
		public string AlItemVendorParts { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.COMMENTS", InBoundData = true)]
		public string AlItemComments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.TRD.DSC.PCTS", InBoundData = true)]
		public string AlItemTrdDscPcts { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.TRD.DSC.AMTS", InBoundData = true)]
		public string AlItemTrdDscAmts { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.FXA.FLAGS", InBoundData = true)]
		public string AlItemFxaFlags { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "AL.ITEM.DELIVERY.DATE", InBoundData = true)]
		public Nullable<DateTime> AlItemDeliveryDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.COMMODITY.CODE", InBoundData = true)]
		public string AlItemCommodityCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.TAX.FORM", InBoundData = true)]
		public string AlItemTaxForm { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.TAX.FORM.CODE", InBoundData = true)]
		public string AlItemTaxFormCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.TAX.FORM.LOC", InBoundData = true)]
		public string AlItemTaxFormLoc { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ITEM.TAX.CODES", InBoundData = true)]
		public string AlItemTaxCodes { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "TX.UPDATE.WEB.PO", GeneratedDateTime = "2/17/2020 8:45:21 PM", User = "anamika_a ")]
	[SctrqDataContract(Application = "CF", DataContractVersion = 1)]
	public class TxUpdateWebPurchaseOrderRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PERSON.ID", InBoundData = true)]        
		public string APersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PO.ID", InBoundData = true)]        
		public string APoId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.VENDOR", InBoundData = true)]        
		public string AVendor { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.VENDOR.IS.PERSON.FLAG", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, InBoundData = true)]        
		public bool AVendorIsPersonFlag { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.AP.TYPE", InBoundData = true)]        
		public string AApType { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.SHIP.TO", InBoundData = true)]        
		public string AShipTo { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PO.COMMODITY.CODE", InBoundData = true)]        
		public string APoCommodityCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CONF.EMAIL.ADDRESSES", InBoundData = true)]        
		public List<string> AlConfEmailAddresses { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.PRINTED.COMMENTS", InBoundData = true)]        
		public List<string> AlPrintedComments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.INTERNAL.COMMENTS", InBoundData = true)]        
		public List<string> AlInternalComments { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.NEXT.APPROVERS", InBoundData = true)]        
		public List<string> AlNextApprovers { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:AL.ITEM.IDS", InBoundData = true)]
		public List<AlUpdatedPoLineItems> AlUpdatedPoLineItems { get; set; }

		public TxUpdateWebPurchaseOrderRequest()
		{	
			AlConfEmailAddresses = new List<string>();
			AlPrintedComments = new List<string>();
			AlInternalComments = new List<string>();
			AlNextApprovers = new List<string>();
			AlUpdatedPoLineItems = new List<AlUpdatedPoLineItems>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "TX.UPDATE.WEB.PO", GeneratedDateTime = "2/17/2020 8:45:21 PM", User = "anamika_a ")]
	[SctrqDataContract(Application = "CF", DataContractVersion = 1)]
	public class TxUpdateWebPurchaseOrderResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PO.ID", OutBoundData = true)]        
		public string APoId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ERROR", OutBoundData = true)]        
		public string AError { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ERROR.MESSAGES", OutBoundData = true)]        
		public List<string> AlErrorMessages { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.WARNING", OutBoundData = true)]        
		public string AWarning { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.WARNING.MESSAGES", OutBoundData = true)]        
		public List<string> AlWarningMessages { get; set; }

		public TxUpdateWebPurchaseOrderResponse()
		{	
			AlErrorMessages = new List<string>();
			AlWarningMessages = new List<string>();
		}
	}
}
