//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 12/20/2019 4:20:28 PM by user sreedharpuligundla
//
//     Type: CTX
//     Transaction ID: GET.MY.CASE.CONTRIBUTIONS
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Base.Transactions
{
	[DataContract]
	public class MyCaseContributions
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.IDS", OutBoundData = true)]
		public string AlCaseIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.STUDENTS", OutBoundData = true)]
		public string AlStudents { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.NAMES", OutBoundData = true)]
		public string AlNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.ITEM.IDS", OutBoundData = true)]
		public string AlCaseItemIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.SUMMARIES", OutBoundData = true)]
		public string AlCaseSummaries { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.STATUSES", OutBoundData = true)]
		public string AlCaseStatuses { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.OWNERS", OutBoundData = true)]
		public string AlCaseOwners { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.SUBJECT.IDS", OutBoundData = true)]
		public string AlCaseSubjectIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.TYPES", OutBoundData = true)]
		public string AlCaseTypes { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "AL.CASE.ITEM.DATES", OutBoundData = true)]
		public Nullable<DateTime> AlCaseItemDates { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "AL.DATE.CREATED", OutBoundData = true)]
		public Nullable<DateTime> AlDateCreated { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CATEGORIES", OutBoundData = true)]
		public string AlCategories { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CATEGORY.DESCRIPTIONS", OutBoundData = true)]
		public string AlCategoryDescriptions { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.MY.CASE.CONTRIBUTIONS", GeneratedDateTime = "12/20/2019 4:20:28 PM", User = "sreedharpuligundla")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class GetMyCaseContributionsRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ID", InBoundData = true)]        
		public string AId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.EXCL.OLD", InBoundData = true)]        
		public string AExclOld { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.EXCL.OWNED", InBoundData = true)]        
		public string AExclOwned { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.EXCL.CLOSED", InBoundData = true)]        
		public string AExclClosed { get; set; }

		public GetMyCaseContributionsRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.MY.CASE.CONTRIBUTIONS", GeneratedDateTime = "12/20/2019 4:20:28 PM", User = "sreedharpuligundla")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class GetMyCaseContributionsResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ERROR.MESSAGES", OutBoundData = true)]        
		public List<string> AlErrorMessages { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:AL.CASE.IDS", OutBoundData = true)]
		public List<MyCaseContributions> MyCaseContributions { get; set; }

		public GetMyCaseContributionsResponse()
		{	
			AlErrorMessages = new List<string>();
			MyCaseContributions = new List<MyCaseContributions>();
		}
	}
}
