//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 3/9/2020 1:00:16 PM by user spirest
//
//     Type: CTX
//     Transaction ID: GET.RA.CASE.CATEGORY.ORG.ROLES
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Base.Transactions
{
	[DataContract]
	public class CaseCategoryOrgRoles
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.CATEGORY.IDS", OutBoundData = true)]
		public string AlCaseCategoryIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ORG.ROLE.IDS", OutBoundData = true)]
		public string AlOrgRoleIds { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ORG.ROLE.NAMES", OutBoundData = true)]
		public string AlOrgRoleNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.INITIAL.ASSIGNMENT", OutBoundData = true)]
		public string AlInitialAssignment { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.REASSIGNMENT", OutBoundData = true)]
		public string AlReassignment { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.REPORTING", OutBoundData = true)]
		public string AlReporting { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.RA.CASE.CATEGORY.ORG.ROLES", GeneratedDateTime = "3/9/2020 1:00:16 PM", User = "spirest")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class GetRaCaseCategoryOrgRolesRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.CASE.CATEGORY.IDS.IN", InBoundData = true)]        
		public List<string> AlCaseCategoryIdsIn { get; set; }

		public GetRaCaseCategoryOrgRolesRequest()
		{	
			AlCaseCategoryIdsIn = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.RA.CASE.CATEGORY.ORG.ROLES", GeneratedDateTime = "3/9/2020 1:00:16 PM", User = "spirest")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class GetRaCaseCategoryOrgRolesResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:AL.ORG.ROLE.IDS", OutBoundData = true)]
		public List<CaseCategoryOrgRoles> CaseCategoryOrgRoles { get; set; }

		public GetRaCaseCategoryOrgRolesResponse()
		{	
			CaseCategoryOrgRoles = new List<CaseCategoryOrgRoles>();
		}
	}
}
