//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 4/5/2018 11:47:54 AM by user balvano3
//
//     Type: CTX
//     Transaction ID: UPDATE.ADDRESS
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Base.Transactions
{
	[DataContract]
	public class AddressErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.ADDRESS", GeneratedDateTime = "4/5/2018 11:47:54 AM", User = "balvano3")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 2)]
	public class UpdateAddressRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADDRESS.ID", InBoundData = true)]        
		public string AddressId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADDRESS.LINES", InBoundData = true)]        
		public List<string> AddressLines { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "COUNTRY", InBoundData = true)]        
		public string Country { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADDRESS.CHAPTER", InBoundData = true)]        
		public List<string> GeographicArea { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CARRIER.ROUTE", InBoundData = true)]        
		public string CarrierRoute { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INTL.LOCALITY", InBoundData = true)]        
		public string IntlLocality { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INTL.REGION", InBoundData = true)]        
		public string IntlRegion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INTL.SUB.REGION", InBoundData = true)]        
		public string IntlSubRegion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INTL.POSTAL.CODE", InBoundData = true)]        
		public string IntlPostalCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "DELIVERY.POINT", InBoundData = true)]        
		public string DeliveryPoint { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CORRECTION.DIGIT", InBoundData = true)]        
		public string CorrectionDigit { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N6}")]
		[SctrqDataMember(AppServerName = "LATITUDE", InBoundData = true)]        
		public Nullable<Decimal> Latitude { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N6}")]
		[SctrqDataMember(AppServerName = "LONGITUDE", InBoundData = true)]        
		public Nullable<Decimal> Longitude { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "ADDRESS.GUID", InBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		public UpdateAddressRequest()
		{	
			AddressLines = new List<string>();
			GeographicArea = new List<string>();
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.ADDRESS", GeneratedDateTime = "4/5/2018 11:47:54 AM", User = "balvano3")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 2)]
	public class UpdateAddressResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADDRESS.ID", OutBoundData = true)]        
		public string AddressId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "ADDRESS.GUID", OutBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.OCCURRED", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, OutBoundData = true)]        
		public bool ErrorOccurred { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<AddressErrors> AddressErrors { get; set; }

		public UpdateAddressResponse()
		{	
			AddressErrors = new List<AddressErrors>();
		}
	}
}
