//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 8/1/2019 9:02:27 AM by user bsf1
//
//     Type: CTX
//     Transaction ID: UPDATE.INSTITUTIONS.ATTEND
//     Application: CORE
//     Environment: dvcoll-2019
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Base.Transactions
{
	[DataContract]
	public class UpdateInstitutionsAttendErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }
	}

	[DataContract]
	public class DatesAttended
	{
		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "START.DATES", InBoundData = true)]
		public Nullable<DateTime> StartDates { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "END.DATES", InBoundData = true)]
		public Nullable<DateTime> EndDates { get; set; }
	}

	[DataContract]
	public class YearsAttended
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "YEAR.ATTEND.START", InBoundData = true)]
		public Nullable<int> YearsAttendedStart { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "YEAR.ATTEND.END", InBoundData = true)]
		public Nullable<int> YearsAttendedEnd { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.INSTITUTIONS.ATTEND", GeneratedDateTime = "8/1/2019 9:02:27 AM", User = "bsf1")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class UpdateInstitutionsAttendRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INSTA.PERSON.ID", InBoundData = true)]        
		public string PersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INSTA.INSTITUTIONS.ID", InBoundData = true)]        
		public string InstitutionsId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N3}")]
		[SctrqDataMember(AppServerName = "INSTA.EXT.GPA", InBoundData = true)]        
		public Nullable<Decimal> PerformanceMeasure { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INSTA.RANK.DENOMINATOR", InBoundData = true)]        
		public Nullable<int> ClassSize { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INSTA.RANK.NUMERATOR", InBoundData = true)]        
		public Nullable<int> ClassRank { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "INSTA.RANK.PERCENT", InBoundData = true)]        
		public Nullable<Decimal> ClassPercentile { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "INSTA.EXT.CREDITS", InBoundData = true)]        
		public Nullable<Decimal> TotalCredits { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "INSTA.INTG.HS.GRAD.DATE", InBoundData = true)]        
		public Nullable<DateTime> HsGradDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", InBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:START.DATES", InBoundData = true)]
		public List<DatesAttended> DatesAttended { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:YEAR.ATTEND.START", InBoundData = true)]
		public List<YearsAttended> YearsAttended { get; set; }

		public UpdateInstitutionsAttendRequest()
		{	
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
			DatesAttended = new List<DatesAttended>();
			YearsAttended = new List<YearsAttended>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.INSTITUTIONS.ATTEND", GeneratedDateTime = "8/1/2019 9:02:27 AM", User = "bsf1")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class UpdateInstitutionsAttendResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INSTA.PERSON.ID", OutBoundData = true)]        
		public string PersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "INSTA.INSTITUTIONS.ID", OutBoundData = true)]        
		public string InstitutionsId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", OutBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, OutBoundData = true)]        
		public bool Error { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<UpdateInstitutionsAttendErrors> UpdateInstitutionsAttendErrors { get; set; }

		public UpdateInstitutionsAttendResponse()
		{	
			UpdateInstitutionsAttendErrors = new List<UpdateInstitutionsAttendErrors>();
		}
	}
}
