//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 7/25/2019 2:49:39 PM by user dvcoll-srm
//
//     Type: CTX
//     Transaction ID: UPDATE.ACAD.CREDENTIALS
//     Application: CORE
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Base.Transactions
{
	[DataContract]
	public class UpdateAcadCredentialsErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.ACAD.CREDENTIALS", GeneratedDateTime = "7/25/2019 2:49:39 PM", User = "dvcoll-srm")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class UpdateAcadCredentialsRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.PERSON.ID", InBoundData = true)]        
		public string PersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.INSTITUTIONS.ID", InBoundData = true)]        
		public string InstitutionsId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.CREDENTIALS.ID", InBoundData = true)]        
		public string CredentialsId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.DEGREE", InBoundData = true)]        
		public string Degree { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "ACAD.DEGREE.DATE", InBoundData = true)]        
		public Nullable<DateTime> DegreeDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.CCD", InBoundData = true)]        
		public List<string> Ccd { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "ACAD.CCD.DATE", InBoundData = true)]        
		public List<Nullable<DateTime>> CcdDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.MAJORS", InBoundData = true)]        
		public List<string> Majors { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.MINORS", InBoundData = true)]        
		public List<string> Minors { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.SPECIALIZATION", InBoundData = true)]        
		public List<string> Specialization { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "ACAD.START.DATE", InBoundData = true)]        
		public Nullable<DateTime> StartDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "ACAD.END.DATE", InBoundData = true)]        
		public Nullable<DateTime> EndDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N3}")]
		[SctrqDataMember(AppServerName = "ACAD.GPA", InBoundData = true)]        
		public Nullable<Decimal> Gpa { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.HONORS", InBoundData = true)]        
		public List<string> Honors { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.RANK.DENOMINATOR", InBoundData = true)]        
		public Nullable<int> RankDenominator { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.RANK.NUMERATOR", InBoundData = true)]        
		public Nullable<int> RankNumerator { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "ACAD.RANK.PERCENT", InBoundData = true)]        
		public Nullable<Decimal> RankPercent { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.THESIS", InBoundData = true)]        
		public string Thesis { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", InBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		public UpdateAcadCredentialsRequest()
		{	
			Ccd = new List<string>();
			CcdDate = new List<Nullable<DateTime>>();
			Majors = new List<string>();
			Minors = new List<string>();
			Specialization = new List<string>();
			Honors = new List<string>();
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.ACAD.CREDENTIALS", GeneratedDateTime = "7/25/2019 2:49:39 PM", User = "dvcoll-srm")]
	[SctrqDataContract(Application = "CORE", DataContractVersion = 1)]
	public class UpdateAcadCredentialsResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACAD.CREDENTIALS.ID", OutBoundData = true)]        
		public string CredentialsId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", OutBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, OutBoundData = true)]        
		public bool Error { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<UpdateAcadCredentialsErrors> UpdateAcadCredentialsErrors { get; set; }

		public UpdateAcadCredentialsResponse()
		{	
			UpdateAcadCredentialsErrors = new List<UpdateAcadCredentialsErrors>();
		}
	}
}
