//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 1/23/2018 10:50:46 AM by user otorres
//
//     Type: ENTITY
//     Entity: PELL.ACYR
//     Application: ST
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Finance.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "PellAcyr")]
	[ColleagueDataContract(GeneratedDateTime = "1/23/2018 10:50:46 AM", User = "otorres")]
	[EntityDataContract(EntityName = "PELL.ACYR", EntityType = "PHYS")]
	public class PellAcyr : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: PELL.DISB.DATES
		/// </summary>
		[DataMember(Order = 4, Name = "PELL.DISB.DATES")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<DateTime?> PellDisbDates { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.DISB.WEIGHTS
		/// </summary>
		[DataMember(Order = 5, Name = "PELL.DISB.WEIGHTS")]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<Decimal?> PellDisbWeights { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.DISB.AMOUNTS
		/// </summary>
		[DataMember(Order = 6, Name = "PELL.DISB.AMOUNTS")]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<Decimal?> PellDisbAmounts { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.DISB.AWARD.PERIODS
		/// </summary>
		[DataMember(Order = 7, Name = "PELL.DISB.AWARD.PERIODS")]
		public List<string> PellDisbAwardPeriods { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.ACT.DISB.DATES
		/// </summary>
		[DataMember(Order = 8, Name = "PELL.ACT.DISB.DATES")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<DateTime?> PellActDisbDates { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.ACT.DISB.AMOUNTS
		/// </summary>
		[DataMember(Order = 9, Name = "PELL.ACT.DISB.AMOUNTS")]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<Decimal?> PellActDisbAmounts { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.INIT.DISB.DATES
		/// </summary>
		[DataMember(Order = 21, Name = "PELL.INIT.DISB.DATES")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public List<DateTime?> PellInitDisbDates { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.INIT.ENRL.STATUS
		/// </summary>
		[DataMember(Order = 22, Name = "PELL.INIT.ENRL.STATUS")]
		public List<string> PellInitEnrlStatus { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.INIT.CIP.CODE
		/// </summary>
		[DataMember(Order = 23, Name = "PELL.INIT.CIP.CODE")]
		public List<string> PellInitCipCode { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.INIT.PROGRAMS
		/// </summary>
		[DataMember(Order = 31, Name = "PELL.INIT.PROGRAMS")]
		public List<string> PellInitPrograms { get; set; }
		
		/// <summary>
		/// CDD Name: PELL.SPECIAL.PROGRAM.TYPE
		/// </summary>
		[DataMember(Order = 32, Name = "PELL.SPECIAL.PROGRAM.TYPE")]
		public List<string> PellSpecialProgramType { get; set; }
		
		/// <summary>
		/// Entity assocation member
		/// </summary>
		[DataMember]
		public List<PellAcyrPellDisbs> PellDisbsEntityAssociation { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			// EntityAssociation Name: PELL.DISBS
			
			PellDisbsEntityAssociation = new List<PellAcyrPellDisbs>();
			// Set max length to the count of controller when initializing.
			//Update max length if any of the association members has higher length than controller length
			if(PellDisbDates != null)
			{
				int numPellDisbs = PellDisbDates.Count;
				if (PellDisbWeights !=null && PellDisbWeights.Count > numPellDisbs) numPellDisbs = PellDisbWeights.Count;
				if (PellDisbAmounts !=null && PellDisbAmounts.Count > numPellDisbs) numPellDisbs = PellDisbAmounts.Count;
				if (PellDisbAwardPeriods !=null && PellDisbAwardPeriods.Count > numPellDisbs) numPellDisbs = PellDisbAwardPeriods.Count;
				if (PellActDisbDates !=null && PellActDisbDates.Count > numPellDisbs) numPellDisbs = PellActDisbDates.Count;
				if (PellActDisbAmounts !=null && PellActDisbAmounts.Count > numPellDisbs) numPellDisbs = PellActDisbAmounts.Count;
				if (PellInitDisbDates !=null && PellInitDisbDates.Count > numPellDisbs) numPellDisbs = PellInitDisbDates.Count;
				if (PellInitEnrlStatus !=null && PellInitEnrlStatus.Count > numPellDisbs) numPellDisbs = PellInitEnrlStatus.Count;
				if (PellInitCipCode !=null && PellInitCipCode.Count > numPellDisbs) numPellDisbs = PellInitCipCode.Count;
				if (PellInitPrograms !=null && PellInitPrograms.Count > numPellDisbs) numPellDisbs = PellInitPrograms.Count;
				if (PellSpecialProgramType !=null && PellSpecialProgramType.Count > numPellDisbs) numPellDisbs = PellSpecialProgramType.Count;

				for (int i = 0; i < numPellDisbs; i++)
				{

					DateTime? value0 = null;
					if (PellDisbDates != null && i < PellDisbDates.Count)
					{
						value0 = PellDisbDates[i];
					}


					Decimal? value1 = null;
					if (PellDisbWeights != null && i < PellDisbWeights.Count)
					{
						value1 = PellDisbWeights[i];
					}


					Decimal? value2 = null;
					if (PellDisbAmounts != null && i < PellDisbAmounts.Count)
					{
						value2 = PellDisbAmounts[i];
					}


					string value3 = "";
					if (PellDisbAwardPeriods != null && i < PellDisbAwardPeriods.Count)
					{
						value3 = PellDisbAwardPeriods[i];
					}


					DateTime? value4 = null;
					if (PellActDisbDates != null && i < PellActDisbDates.Count)
					{
						value4 = PellActDisbDates[i];
					}


					Decimal? value5 = null;
					if (PellActDisbAmounts != null && i < PellActDisbAmounts.Count)
					{
						value5 = PellActDisbAmounts[i];
					}


					DateTime? value6 = null;
					if (PellInitDisbDates != null && i < PellInitDisbDates.Count)
					{
						value6 = PellInitDisbDates[i];
					}


					string value7 = "";
					if (PellInitEnrlStatus != null && i < PellInitEnrlStatus.Count)
					{
						value7 = PellInitEnrlStatus[i];
					}


					string value8 = "";
					if (PellInitCipCode != null && i < PellInitCipCode.Count)
					{
						value8 = PellInitCipCode[i];
					}


					string value9 = "";
					if (PellInitPrograms != null && i < PellInitPrograms.Count)
					{
						value9 = PellInitPrograms[i];
					}


					string value10 = "";
					if (PellSpecialProgramType != null && i < PellSpecialProgramType.Count)
					{
						value10 = PellSpecialProgramType[i];
					}

					PellDisbsEntityAssociation.Add(new PellAcyrPellDisbs( value0, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10));
				}
			}
			   
		}
	}
	
	// EntityAssociation classes
	
	[Serializable]
	public class PellAcyrPellDisbs
	{
		public DateTime? PellDisbDatesAssocMember;	
		public Decimal? PellDisbWeightsAssocMember;	
		public Decimal? PellDisbAmountsAssocMember;	
		public string PellDisbAwardPeriodsAssocMember;	
		public DateTime? PellActDisbDatesAssocMember;	
		public Decimal? PellActDisbAmountsAssocMember;	
		public DateTime? PellInitDisbDatesAssocMember;	
		public string PellInitEnrlStatusAssocMember;	
		public string PellInitCipCodeAssocMember;	
		public string PellInitProgramsAssocMember;	
		public string PellSpecialProgramTypeAssocMember;	
		public PellAcyrPellDisbs() {}
		public PellAcyrPellDisbs(
			DateTime? inPellDisbDates,
			Decimal? inPellDisbWeights,
			Decimal? inPellDisbAmounts,
			string inPellDisbAwardPeriods,
			DateTime? inPellActDisbDates,
			Decimal? inPellActDisbAmounts,
			DateTime? inPellInitDisbDates,
			string inPellInitEnrlStatus,
			string inPellInitCipCode,
			string inPellInitPrograms,
			string inPellSpecialProgramType)
		{
			PellDisbDatesAssocMember = inPellDisbDates;
			PellDisbWeightsAssocMember = inPellDisbWeights;
			PellDisbAmountsAssocMember = inPellDisbAmounts;
			PellDisbAwardPeriodsAssocMember = inPellDisbAwardPeriods;
			PellActDisbDatesAssocMember = inPellActDisbDates;
			PellActDisbAmountsAssocMember = inPellActDisbAmounts;
			PellInitDisbDatesAssocMember = inPellInitDisbDates;
			PellInitEnrlStatusAssocMember = inPellInitEnrlStatus;
			PellInitCipCodeAssocMember = inPellInitCipCode;
			PellInitProgramsAssocMember = inPellInitPrograms;
			PellSpecialProgramTypeAssocMember = inPellSpecialProgramType;
		}
	}
}