//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 1:36:48 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: RCPT.SESSIONS
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.Finance.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "RcptSessions")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 1:36:48 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "RCPT.SESSIONS", EntityType = "PHYS")]
	public class RcptSessions : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: RCPTS.STATUS
		/// </summary>
		[DataMember(Order = 0, Name = "RCPTS.STATUS")]
		public string RcptsStatus { get; set; }
		
		/// <summary>
		/// CDD Name: RCPTS.START.TIME
		/// </summary>
		[DataMember(Order = 1, Name = "RCPTS.START.TIME")]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? RcptsStartTime { get; set; }
		
		/// <summary>
		/// CDD Name: RCPTS.END.DATE
		/// </summary>
		[DataMember(Order = 2, Name = "RCPTS.END.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? RcptsEndDate { get; set; }
		
		/// <summary>
		/// CDD Name: RCPTS.END.TIME
		/// </summary>
		[DataMember(Order = 3, Name = "RCPTS.END.TIME")]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? RcptsEndTime { get; set; }
		
		/// <summary>
		/// CDD Name: RCPT.SESSIONS.ADDOPR
		/// </summary>
		[DataMember(Order = 4, Name = "RCPT.SESSIONS.ADDOPR")]
		public string RcptSessionsAddopr { get; set; }
		
		/// <summary>
		/// CDD Name: RCPT.SESSIONS.ADDDATE
		/// </summary>
		[DataMember(Order = 5, Name = "RCPT.SESSIONS.ADDDATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? RcptSessionsAdddate { get; set; }
		
		/// <summary>
		/// CDD Name: RCPTS.DATE
		/// </summary>
		[DataMember(Order = 8, Name = "RCPTS.DATE")]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[ColleagueDataMember(UseEnvisionInternalFormat = true)]
		public DateTime? RcptsDate { get; set; }
		
		/// <summary>
		/// CDD Name: RCPTS.LOCATION
		/// </summary>
		[DataMember(Order = 12, Name = "RCPTS.LOCATION")]
		public string RcptsLocation { get; set; }
		
		/// <summary>
		/// CDD Name: RCPTS.ECOMMERCE.FLAG
		/// </summary>
		[DataMember(Order = 36, Name = "RCPTS.ECOMMERCE.FLAG")]
		public string RcptsEcommerceFlag { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}