//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 4/16/2018 1:36:22 PM by user asainju1
//
//     Type: CTX
//     Transaction ID: CREATE.UPDATE.MEAL.PLAN.REQ
//     Application: ST
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[DataContract]
	public class CreateUpdateMealPlanReqRequestErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "CREATE.UPDATE.MEAL.PLAN.REQ", GeneratedDateTime = "4/16/2018 1:36:22 PM", User = "asainju1")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class CreateUpdateMealPlanReqRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "MEAL.PLAN.REQ.ID", InBoundData = true)]        
		public string MealPlanReqId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", InBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "PERSON.ID", InBoundData = true)]        
		public string PersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "MEAL.PLAN.ID", InBoundData = true)]        
		public string MealPlanId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ACADEMIC.PERIOD.ID", InBoundData = true)]        
		public string AcademicPeriodId { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "START.ON", InBoundData = true)]        
		public Nullable<DateTime> StartOn { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "END.ON", InBoundData = true)]        
		public Nullable<DateTime> EndOn { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "SUBMITTED.ON", InBoundData = true)]        
		public Nullable<DateTime> SubmittedOn { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "STATUS", InBoundData = true)]        
		public string Status { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "STATUS.DATE", InBoundData = true)]        
		public Nullable<DateTime> StatusDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		public CreateUpdateMealPlanReqRequest()
		{	
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "CREATE.UPDATE.MEAL.PLAN.REQ", GeneratedDateTime = "4/16/2018 1:36:22 PM", User = "asainju1")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class CreateUpdateMealPlanReqResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "MEAL.PLAN.REQ.ID", OutBoundData = true)]        
		public string MealPlanReqId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", OutBoundData = true)]        
		public string Guid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR", OutBoundData = true)]        
		public string Error { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<CreateUpdateMealPlanReqRequestErrors> CreateUpdateMealPlanReqRequestErrors { get; set; }

		public CreateUpdateMealPlanReqResponse()
		{	
			CreateUpdateMealPlanReqRequestErrors = new List<CreateUpdateMealPlanReqRequestErrors>();
		}
	}
}
