//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/5/2017 2:38:53 PM by user dvcoll-schandraseka
//
//     Type: CTX
//     Transaction ID: DELETE.SECTION.XLIST
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[DataContract]
	public class DeleteCrossListErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODE", OutBoundData = true)]
		public string ErrorCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MSG", OutBoundData = true)]
		public string ErrorMsg { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "DELETE.SECTION.XLIST", GeneratedDateTime = "10/5/2017 2:38:53 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class DeleteSectionXlistRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "COURSE.SEC.XLISTS.ID", InBoundData = true)]        
		public string CourseSecXlistsId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "GUID", InBoundData = true)]        
		public string StrGuid { get; set; }

		public DeleteSectionXlistRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "DELETE.SECTION.XLIST", GeneratedDateTime = "10/5/2017 2:38:53 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class DeleteSectionXlistResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODE", OutBoundData = true)]
		public List<DeleteCrossListErrors> DeleteCrossListErrors { get; set; }

		public DeleteSectionXlistResponse()
		{	
			DeleteCrossListErrors = new List<DeleteCrossListErrors>();
		}
	}
}
