//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/5/2017 2:38:44 PM by user dvcoll-schandraseka
//
//     Type: CTX
//     Transaction ID: DELETE.SECTION.FACULTY
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[DataContract]
	public class DeleteSectionInstructorsErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }
	}

	[DataContract]
	public class DeleteSectionInstructorsWarnings
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "WARNING.CODES", OutBoundData = true)]
		public string WarningCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "WARNING.MESSAGES", OutBoundData = true)]
		public string WarningMessages { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "DELETE.SECTION.FACULTY", GeneratedDateTime = "10/5/2017 2:38:44 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class DeleteSectionInstructorsRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "COURSE.SEC.FACULTY.ID", InBoundData = true)]        
		public string CourseSecFacultyId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSF.GUID", InBoundData = true)]        
		public string CsfGuid { get; set; }

		public DeleteSectionInstructorsRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "DELETE.SECTION.FACULTY", GeneratedDateTime = "10/5/2017 2:38:44 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class DeleteSectionInstructorsResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<DeleteSectionInstructorsErrors> DeleteSectionInstructorsErrors { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:WARNING.CODES", OutBoundData = true)]
		public List<DeleteSectionInstructorsWarnings> DeleteSectionInstructorsWarnings { get; set; }

		public DeleteSectionInstructorsResponse()
		{	
			DeleteSectionInstructorsErrors = new List<DeleteSectionInstructorsErrors>();
			DeleteSectionInstructorsWarnings = new List<DeleteSectionInstructorsWarnings>();
		}
	}
}
