//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/5/2017 2:40:30 PM by user dvcoll-schandraseka
//
//     Type: CTX
//     Transaction ID: GET.GRADE.VIEW.RESTRICTIONS
//     Application: ST
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.GRADE.VIEW.RESTRICTIONS", GeneratedDateTime = "10/5/2017 2:40:30 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class GetGradeViewRestrictionsRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PERSON.ID", InBoundData = true)]        
		public string PersonId { get; set; }

		public GetGradeViewRestrictionsRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "GET.GRADE.VIEW.RESTRICTIONS", GeneratedDateTime = "10/5/2017 2:40:30 PM", User = "dvcoll-schandraseka")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class GetGradeViewRestrictionsResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "IS.RESTRICTED", OutBoundData = true)]        
		public string IsRestricted { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "REASONS", OutBoundData = true)]        
		public List<string> Reasons { get; set; }

		public GetGradeViewRestrictionsResponse()
		{	
			Reasons = new List<string>();
		}
	}
}
