//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 7/23/2019 2:28:20 AM by user ramyajoshi
//
//     Type: CTX
//     Transaction ID: TX.CHANGE.OF.PROGRAM
//     Application: ST
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "TX.CHANGE.OF.PROGRAM", GeneratedDateTime = "7/23/2019 2:28:20 AM", User = "ramyajoshi")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class TxChangeOfProgramRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.PERSON.ID", InBoundData = true)]        
		public string APersonId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.ACAD.PROGRAM", InBoundData = true)]        
		public string AAcadProgram { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.CATALOG", InBoundData = true)]        
		public string ACatalog { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.ACTION", InBoundData = true)]        
		public string AAction { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.START.DATE", InBoundData = true)]        
		public string AStartDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.ACTIVE.PROGRAMS", InBoundData = true)]        
		public List<string> AActivePrograms { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.COPY.ED.PLAN", InBoundData = true)]        
		public string ACopyEdPlan { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.END.DATES", InBoundData = true)]        
		public List<string> AlEndDates { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.DEPARTMENT", InBoundData = true)]        
		public string ADept { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.LOCATION", InBoundData = true)]        
		public string ALocation { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.CREATE.APPL.FLAG", InBoundData = true)]        
		public string ACreateApplFlag { get; set; }

		public TxChangeOfProgramRequest()
		{	
			AActivePrograms = new List<string>();
			AlEndDates = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "TX.CHANGE.OF.PROGRAM", GeneratedDateTime = "7/23/2019 2:28:20 AM", User = "ramyajoshi")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class TxChangeOfProgramResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ERROR.MESSAGE", OutBoundData = true)]        
		public string AErrorMessage { get; set; }

		public TxChangeOfProgramResponse()
		{	
		}
	}
}
