//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/19/2017 6:10:11 PM by user gtt_dvcoll_wstst01
//
//     Type: CTX
//     Transaction ID: TX.NOTIFY.ST.PDF.ACCESS
//     Application: ST
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "TX.NOTIFY.ST.PDF.ACCESS", GeneratedDateTime = "10/19/2017 6:10:11 PM", User = "gtt_dvcoll_wstst01")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class TxNotifyStPdfAccessRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.TAX.FORM.PDF.ID", InBoundData = true)]        
		public string TaxFormPdfId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.PDF.PERSON.ID", InBoundData = true)]        
		public string PdfPersonId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.TAX.FORM", InBoundData = true)]        
		public string TaxForm { get; set; }

		public TxNotifyStPdfAccessRequest()
		{	
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "TX.NOTIFY.ST.PDF.ACCESS", GeneratedDateTime = "10/19/2017 6:10:11 PM", User = "gtt_dvcoll_wstst01")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class TxNotifyStPdfAccessResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }


		public TxNotifyStPdfAccessResponse()
		{	
		}
	}
}
