//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 3/22/2018 1:10:54 PM by user mbscs
//
//     Type: CTX
//     Transaction ID: UPDATE.INSTRUCTIONAL.EVENT
//     Application: ST
//     Environment: dvcoll_wstst01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[DataContract]
	public class UpdateInstructionalEventErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODES", OutBoundData = true)]
		public string ErrorCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MESSAGES", OutBoundData = true)]
		public string ErrorMessages { get; set; }
	}

	[DataContract]
	public class UpdateInstructionalEventWarnings
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "WARNING.CODES", OutBoundData = true)]
		public string WarningCodes { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "WARNING.MESSAGES", OutBoundData = true)]
		public string WarningMessages { get; set; }
	}

	[DataContract]
	public class FacultyRoster
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "FAC.CSF.ID", InBoundData = true)]
		public string FacCsfId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FAC.INSTR.METHOD", InBoundData = true)]
		public string FacInstrMethod { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FAC.FACULTY", InBoundData = true)]
		public string FacFaculty { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "FAC.START.DATE", InBoundData = true)]
		public Nullable<DateTime> FacStartDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "FAC.END.DATE", InBoundData = true)]
		public Nullable<DateTime> FacEndDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FAC.FACULTY.PCT", InBoundData = true)]
		public Nullable<Decimal> FacFacultyPct { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "FAC.FACULTY.LOAD", InBoundData = true)]
		public Nullable<Decimal> FacFacultyLoad { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FAC.PAC.LP.ASGMT", InBoundData = true)]
		public string FacPacLpAsgmt { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "FAC.TEACHING.ARRANGEMENT", InBoundData = true)]
		public string FacTeachingArrangement { get; set; }
	}

	[DataContract]
	public class SecMeet
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "SECMEET.ID", InBoundData = true)]
		public string SecmeetId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "SECMEET.FACULTY", InBoundData = true)]
		public string SecmeetFaculty { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.INSTRUCTIONAL.EVENT", GeneratedDateTime = "3/22/2018 1:10:54 PM", User = "mbscs")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class UpdateInstructionalEventRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "COURSE.SEC.MEETING.ID", InBoundData = true)]        
		public string CourseSecMeetingId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.COURSE.SECTION", InBoundData = true)]        
		public string CsmCourseSection { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.INSTR.METHOD", InBoundData = true)]        
		public string CsmInstrMethod { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "CSM.START.DATE", InBoundData = true)]        
		public Nullable<DateTime> CsmStartDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "CSM.END.DATE", InBoundData = true)]        
		public Nullable<DateTime> CsmEndDate { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.FREQUENCY", InBoundData = true)]        
		public string CsmFrequency { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[SctrqDataMember(AppServerName = "CSM.START.TIME", InBoundData = true)]        
		public Nullable<DateTime> CsmStartTime { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[SctrqDataMember(AppServerName = "CSM.END.TIME", InBoundData = true)]        
		public Nullable<DateTime> CsmEndTime { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.BLDG", InBoundData = true)]        
		public string CsmBldg { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.ROOM", InBoundData = true)]        
		public string CsmRoom { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.SUNDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmSunday { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.MONDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmMonday { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.TUESDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmTuesday { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.WEDNESDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmWednesday { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.THURSDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmThursday { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.FRIDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmFriday { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.SATURDAY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.YesNo, InBoundData = true)]        
		public Nullable<bool> CsmSaturday { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:N2}")]
		[SctrqDataMember(AppServerName = "CSM.LOAD", InBoundData = true)]        
		public Nullable<Decimal> CsmLoad { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.FACULTY", InBoundData = true)]        
		public List<string> CsmFaculty { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "CSM.GUID", InBoundData = true)]        
		public string CsmGuid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OVERRIDE.ROOM.CAPACITY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, InBoundData = true)]        
		public bool OverrideRoomCapacity { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OVERRIDE.ROOM.AVAILABILITY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, InBoundData = true)]        
		public bool OverrideRoomAvailability { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OVERRIDE.FACULTY.AVAILABILITY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, InBoundData = true)]        
		public bool OverrideFacultyAvailability { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "OVERRIDE.FACULTY.CAPACITY", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, InBoundData = true)]        
		public bool OverrideFacultyCapacity { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:FAC.CSF.ID", InBoundData = true)]
		public List<FacultyRoster> FacultyRoster { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:SECMEET.ID", InBoundData = true)]
		public List<SecMeet> SecMeet { get; set; }

		public UpdateInstructionalEventRequest()
		{	
			CsmFaculty = new List<string>();
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
			FacultyRoster = new List<FacultyRoster>();
			SecMeet = new List<SecMeet>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.INSTRUCTIONAL.EVENT", GeneratedDateTime = "3/22/2018 1:10:54 PM", User = "mbscs")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class UpdateInstructionalEventResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "COURSE.SEC.MEETING.ID", OutBoundData = true)]        
		public string CourseSecMeetingId { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODES", OutBoundData = true)]
		public List<UpdateInstructionalEventErrors> UpdateInstructionalEventErrors { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:WARNING.CODES", OutBoundData = true)]
		public List<UpdateInstructionalEventWarnings> UpdateInstructionalEventWarnings { get; set; }

		public UpdateInstructionalEventResponse()
		{	
			UpdateInstructionalEventErrors = new List<UpdateInstructionalEventErrors>();
			UpdateInstructionalEventWarnings = new List<UpdateInstructionalEventWarnings>();
		}
	}
}
