//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 4/9/2018 1:29:03 PM by user balvano3
//
//     Type: CTX
//     Transaction ID: UPDATE.ADM.APPL.STATUSES
//     Application: ST
//     Environment: dvcoll
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[DataContract]
	public class ApplicationStatusErrors
	{
		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.MSG", OutBoundData = true)]
		public string ErrorMsg { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ERROR.CODE", OutBoundData = true)]
		public string ErrorCode { get; set; }
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.ADM.APPL.STATUSES", GeneratedDateTime = "4/9/2018 1:29:03 PM", User = "balvano3")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class UpdateAdmApplStatusesRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADMDEC.GUID", InBoundData = true)]        
		public string AdmdecGuid { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "ADMDEC.APPLICATION", InBoundData = true)]        
		public string AdmdecApplication { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADMDEC.STATUS", InBoundData = true)]        
		public string AdmdecStatus { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:d}")]
		[SctrqDataMember(AppServerName = "ADMDEC.DATE", InBoundData = true)]        
		public Nullable<DateTime> AdmdecDate { get; set; }

		[DataMember]
		[DisplayFormat(DataFormatString = "{0:T}")]
		[SctrqDataMember(AppServerName = "ADMDEC.TIME", InBoundData = true)]        
		public Nullable<DateTime> AdmdecTime { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.NAMES", InBoundData = true)]        
		public List<string> ExtendedNames { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "EXTENDED.VALUES", InBoundData = true)]        
		public List<string> ExtendedValues { get; set; }

		public UpdateAdmApplStatusesRequest()
		{	
			ExtendedNames = new List<string>();
			ExtendedValues = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.ADM.APPL.STATUSES", GeneratedDateTime = "4/9/2018 1:29:03 PM", User = "balvano3")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class UpdateAdmApplStatusesResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "ADMDEC.GUID", OutBoundData = true)]        
		public string AdmdecGuid { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "Grp:ERROR.CODE", OutBoundData = true)]
		public List<ApplicationStatusErrors> ApplicationStatusErrors { get; set; }

		public UpdateAdmApplStatusesResponse()
		{	
			ApplicationStatusErrors = new List<ApplicationStatusErrors>();
		}
	}
}
