//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 5/6/2019 1:00:44 PM by user jmansfield
//
//     Type: CTX
//     Transaction ID: UPDATE.GRADUATION.APPLICATION
//     Application: ST
//     Environment: dvcoll_wstst01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;

namespace Ellucian.Colleague.Data.Student.Transactions
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.GRADUATION.APPLICATION", GeneratedDateTime = "5/6/2019 1:00:44 PM", User = "jmansfield")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class UpdateGraduationApplicationRequest
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.STUDENT.ID", InBoundData = true)]        
		public string StudentId { get; set; }

		[DataMember(IsRequired = true)]
		[SctrqDataMember(AppServerName = "A.PROGRAM.CODE", InBoundData = true)]        
		public string ProgramCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.COMMENCEMENT.SITE", InBoundData = true)]        
		public string CommencementSite { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.DIPLOMA.NAME", InBoundData = true)]        
		public string DiplomaName { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MAIL.DIPLOMA.ADDRESS.LINES", InBoundData = true)]        
		public List<string> MailDiplomaAddressLines { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MAIL.DIPLOMA.CITY", InBoundData = true)]        
		public string MailDiplomaCity { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MAIL.DIPLOMA.STATE", InBoundData = true)]        
		public string MailDiplomaState { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MAIL.DIPLOMA.POSTAL.CODE", InBoundData = true)]        
		public string MailDiplomaPostalCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MAIL.DIPLOMA.COUNTRY.CODE", InBoundData = true)]        
		public string MailDiplomaCountryCode { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.CAP.SIZE", InBoundData = true)]        
		public string CapSize { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.GOWN.SIZE", InBoundData = true)]        
		public string GownSize { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.HOMETOWN", InBoundData = true)]        
		public string Hometown { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.INCLUDE.NAME.IN.PROGRAM", InBoundData = true)]        
		public string IncludeNameInProgram { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.NUMBER.OF.GUESTS", InBoundData = true)]        
		public Nullable<int> NumberOfGuests { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PHONETIC.SPELLING", InBoundData = true)]        
		public string PhoneticSpelling { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.WILL.PICKUP.DIPLOMA", InBoundData = true)]        
		public string WillPickupDiploma { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ATTEND.COMMENCEMENT", InBoundData = true)]        
		public string AttendCommencement { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.MILITARY.STATUS", InBoundData = true)]        
		public string MilitaryStatus { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "AL.SPECIAL.ACCOMMODATIONS", InBoundData = true)]        
		public List<string> SpecialAccommodations { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.PRIMARY.LOCATION", InBoundData = true)]        
		public string PrimaryLocation { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.GRADUATION.TERM", InBoundData = true)]        
		public string AGraduationTerm { get; set; }

		public UpdateGraduationApplicationRequest()
		{	
			MailDiplomaAddressLines = new List<string>();
			SpecialAccommodations = new List<string>();
		}
	}

	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract]
	[ColleagueDataContract(ColleagueId = "UPDATE.GRADUATION.APPLICATION", GeneratedDateTime = "5/6/2019 1:00:44 PM", User = "jmansfield")]
	[SctrqDataContract(Application = "ST", DataContractVersion = 1)]
	public class UpdateGraduationApplicationResponse
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ERROR.OCCURRED", UseEnvisionBooleanConventions = EnvisionBooleanTypesEnum.OneZero, OutBoundData = true)]        
		public bool ErrorOccurred { get; set; }

		[DataMember]
		[SctrqDataMember(AppServerName = "A.ERROR.MESSAGE", OutBoundData = true)]        
		public string ErrorMessage { get; set; }

		public UpdateGraduationApplicationResponse()
		{	
		}
	}
}
