//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 1:16:37 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: CFWEB.DEFAULTS
//     Application: CF
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.ColleagueFinance.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "CfwebDefaults")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 1:16:37 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "CFWEB.DEFAULTS", EntityType = "PERM")]
	public class CfwebDefaults : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: CFWEB.CKR.COST.CENTER.COMPS
		/// </summary>
		[DataMember(Order = 30, Name = "CFWEB.CKR.COST.CENTER.COMPS")]
		public List<string> CfwebCkrCostCenterComps { get; set; }
		
		/// <summary>
		/// CDD Name: CFWEB.CKR.COST.CENTER.DESCS
		/// </summary>
		[DataMember(Order = 31, Name = "CFWEB.CKR.COST.CENTER.DESCS")]
		public List<string> CfwebCkrCostCenterDescs { get; set; }
		
		/// <summary>
		/// CDD Name: CFWEB.CKR.OBJECT.CODE.COMPS
		/// </summary>
		[DataMember(Order = 32, Name = "CFWEB.CKR.OBJECT.CODE.COMPS")]
		public List<string> CfwebCkrObjectCodeComps { get; set; }
		
		/// <summary>
		/// CDD Name: CFWEB.CKR.OBJECT.CODE.DESCS
		/// </summary>
		[DataMember(Order = 33, Name = "CFWEB.CKR.OBJECT.CODE.DESCS")]
		public List<string> CfwebCkrObjectCodeDescs { get; set; }
		
		/// <summary>
		/// CDD Name: CFWEB.COST.CENTER.SUBTOTALS
		/// </summary>
		[DataMember(Order = 48, Name = "CFWEB.COST.CENTER.SUBTOTALS")]
		public List<string> CfwebCostCenterSubtotals { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}