//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the DSL/T4 Generator - Version 1.2
//     Last generated on 10/4/2017 1:18:13 PM by user dvcoll-schandraseka
//
//     Type: ENTITY
//     Entity: FISCALYR
//     Application: CF
//     Environment: dvColl
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
using System.CodeDom.Compiler;
using Ellucian.Dmi.Runtime;
using Ellucian.Data.Colleague;

namespace Ellucian.Colleague.Data.ColleagueFinance.DataContracts
{
	[GeneratedCodeAttribute("Colleague Data Contract Generator", "1.2")]
	[DataContract(Name = "Fiscalyr")]
	[ColleagueDataContract(GeneratedDateTime = "10/4/2017 1:18:13 PM", User = "dvcoll-schandraseka")]
	[EntityDataContract(EntityName = "FISCALYR", EntityType = "PERM")]
	public class Fiscalyr : IColleagueEntity
	{
		/// <summary>
		/// Version
		/// </summary>
		[DataMember]
		public int _AppServerVersion { get; set; }

		/// <summary>
		/// Record Key
		/// </summary>
		[DataMember]
		public string Recordkey { get; set; }
		
		public void setKey(string key)
		{
			Recordkey = key;
		}
		
		/// <summary>
		/// CDD Name: CURRENT.FISCAL.YEAR
		/// </summary>
		[DataMember(Order = 0, Name = "CURRENT.FISCAL.YEAR")]
		public int? CurrentFiscalYear { get; set; }
		
		/// <summary>
		/// CDD Name: FISCAL.START.MONTH
		/// </summary>
		[DataMember(Order = 1, Name = "FISCAL.START.MONTH")]
		public int? FiscalStartMonth { get; set; }
		
		/// <summary>
		/// CDD Name: CURRENT.FISCAL.MONTH
		/// </summary>
		[DataMember(Order = 2, Name = "CURRENT.FISCAL.MONTH")]
		public int? CurrentFiscalMonth { get; set; }
		
		/// <summary>
		/// CDD Name: CF.CURRENT.FISCAL.YEAR
		/// </summary>
		[DataMember(Order = 3, Name = "CF.CURRENT.FISCAL.YEAR")]
		public string CfCurrentFiscalYear { get; set; }
		
	
		// build up all the Associated objects and add them to the properties
		public void buildAssociations()
		{	
			   
		}
	}
	
	// EntityAssociation classes
}